// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/ton/ton.proto

package ton

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dest          string                 `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`              // any accepted TON address form
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`         // nanotons
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`             // send-mode flags; default 3 = PAY_FEES_SEPARATELY|IGNORE_ACTION_PHASE_ERRORS
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`        // optional text comment (op=0 payload)
	Bounceable    bool                   `protobuf:"varint,5,opt,name=bounceable,proto3" json:"bounceable,omitempty"` // internal-message bounce flag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_txproto_ton_ton_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ton_ton_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_ton_ton_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Transfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Transfer) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Transfer) GetBounceable() bool {
	if x != nil {
		return x.Bounceable
	}
	return false
}

type SigningInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber uint32                 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // wallet seqno; 0 => attach StateInit (deploy)
	ExpireAt       uint32                 `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`                   // unix seconds
	Transfer       *Transfer              `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_ton_ton_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ton_ton_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_ton_ton_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *SigningInput) GetExpireAt() uint32 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *SigningInput) GetTransfer() *Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

type SigningOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       string                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"` // base64 BoC of the signed external message
	Raw           []byte                 `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`         // raw BoC bytes
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`       // hex repr-hash of the external message cell (poll key)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_ton_ton_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ton_ton_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_ton_ton_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SigningOutput) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_ton_ton_proto protoreflect.FileDescriptor

const file_txproto_ton_ton_proto_rawDesc = "" +
	"\n" +
	"\x15txproto/ton/ton.proto\x12\x12hdwallet.ton.proto\"\x84\x01\n" +
	"\bTransfer\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"bounceable\x18\x05 \x01(\bR\n" +
	"bounceable\"\x8e\x01\n" +
	"\fSigningInput\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\rR\x0esequenceNumber\x12\x1b\n" +
	"\texpire_at\x18\x02 \x01(\rR\bexpireAt\x128\n" +
	"\btransfer\x18\x03 \x01(\v2\x1c.hdwallet.ton.proto.TransferR\btransfer\"e\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB.Z,github.com/ranjbar-dev/hd-wallet/txproto/tonb\x06proto3"

var (
	file_txproto_ton_ton_proto_rawDescOnce sync.Once
	file_txproto_ton_ton_proto_rawDescData []byte
)

func file_txproto_ton_ton_proto_rawDescGZIP() []byte {
	file_txproto_ton_ton_proto_rawDescOnce.Do(func() {
		file_txproto_ton_ton_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_ton_ton_proto_rawDesc), len(file_txproto_ton_ton_proto_rawDesc)))
	})
	return file_txproto_ton_ton_proto_rawDescData
}

var file_txproto_ton_ton_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_txproto_ton_ton_proto_goTypes = []any{
	(*Transfer)(nil),      // 0: hdwallet.ton.proto.Transfer
	(*SigningInput)(nil),  // 1: hdwallet.ton.proto.SigningInput
	(*SigningOutput)(nil), // 2: hdwallet.ton.proto.SigningOutput
}
var file_txproto_ton_ton_proto_depIdxs = []int32{
	0, // 0: hdwallet.ton.proto.SigningInput.transfer:type_name -> hdwallet.ton.proto.Transfer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_txproto_ton_ton_proto_init() }
func file_txproto_ton_ton_proto_init() {
	if File_txproto_ton_ton_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_ton_ton_proto_rawDesc), len(file_txproto_ton_ton_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_ton_ton_proto_goTypes,
		DependencyIndexes: file_txproto_ton_ton_proto_depIdxs,
		MessageInfos:      file_txproto_ton_ton_proto_msgTypes,
	}.Build()
	File_txproto_ton_ton_proto = out.File
	file_txproto_ton_ton_proto_goTypes = nil
	file_txproto_ton_ton_proto_depIdxs = nil
}
