// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/ripple/ripple.proto

package ripple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// XRP (native) payment.
type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`          // drops
	Destination    string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"` // r... address
	DestinationTag int64                  `protobuf:"varint,3,opt,name=destination_tag,json=destinationTag,proto3" json:"destination_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_txproto_ripple_ripple_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ripple_ripple_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_txproto_ripple_ripple_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Payment) GetDestinationTag() int64 {
	if x != nil {
		return x.DestinationTag
	}
	return 0
}

// SigningInput mirrors a minimal subset of TW.Ripple.Proto.SigningInput for a
// native XRP Payment.
type SigningInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Fee                int64                  `protobuf:"varint,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Sequence           uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LastLedgerSequence uint32                 `protobuf:"varint,3,opt,name=last_ledger_sequence,json=lastLedgerSequence,proto3" json:"last_ledger_sequence,omitempty"`
	Account            string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"` // sender r... address
	Flags              uint32                 `protobuf:"varint,5,opt,name=flags,proto3" json:"flags,omitempty"`
	Payment            *Payment               `protobuf:"bytes,6,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_ripple_ripple_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ripple_ripple_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_ripple_ripple_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SigningInput) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SigningInput) GetLastLedgerSequence() uint32 {
	if x != nil {
		return x.LastLedgerSequence
	}
	return 0
}

func (x *SigningInput) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SigningInput) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *SigningInput) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Ripple.Proto.SigningOutput.
type SigningOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       []byte                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"` // serialized signed transaction
	EncodedHex    string                 `protobuf:"bytes,2,opt,name=encoded_hex,json=encodedHex,proto3" json:"encoded_hex,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_ripple_ripple_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ripple_ripple_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_ripple_ripple_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetEncodedHex() string {
	if x != nil {
		return x.EncodedHex
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_ripple_ripple_proto protoreflect.FileDescriptor

const file_txproto_ripple_ripple_proto_rawDesc = "" +
	"\n" +
	"\x1btxproto/ripple/ripple.proto\x12\x15hdwallet.ripple.proto\"l\n" +
	"\aPayment\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12'\n" +
	"\x0fdestination_tag\x18\x03 \x01(\x03R\x0edestinationTag\"\xd8\x01\n" +
	"\fSigningInput\x12\x10\n" +
	"\x03fee\x18\x01 \x01(\x03R\x03fee\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x120\n" +
	"\x14last_ledger_sequence\x18\x03 \x01(\rR\x12lastLedgerSequence\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x14\n" +
	"\x05flags\x18\x05 \x01(\rR\x05flags\x128\n" +
	"\apayment\x18\x06 \x01(\v2\x1e.hdwallet.ripple.proto.PaymentR\apayment\"`\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\x1f\n" +
	"\vencoded_hex\x18\x02 \x01(\tR\n" +
	"encodedHex\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB1Z/github.com/ranjbar-dev/hd-wallet/txproto/rippleb\x06proto3"

var (
	file_txproto_ripple_ripple_proto_rawDescOnce sync.Once
	file_txproto_ripple_ripple_proto_rawDescData []byte
)

func file_txproto_ripple_ripple_proto_rawDescGZIP() []byte {
	file_txproto_ripple_ripple_proto_rawDescOnce.Do(func() {
		file_txproto_ripple_ripple_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_ripple_ripple_proto_rawDesc), len(file_txproto_ripple_ripple_proto_rawDesc)))
	})
	return file_txproto_ripple_ripple_proto_rawDescData
}

var file_txproto_ripple_ripple_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_txproto_ripple_ripple_proto_goTypes = []any{
	(*Payment)(nil),       // 0: hdwallet.ripple.proto.Payment
	(*SigningInput)(nil),  // 1: hdwallet.ripple.proto.SigningInput
	(*SigningOutput)(nil), // 2: hdwallet.ripple.proto.SigningOutput
}
var file_txproto_ripple_ripple_proto_depIdxs = []int32{
	0, // 0: hdwallet.ripple.proto.SigningInput.payment:type_name -> hdwallet.ripple.proto.Payment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_txproto_ripple_ripple_proto_init() }
func file_txproto_ripple_ripple_proto_init() {
	if File_txproto_ripple_ripple_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_ripple_ripple_proto_rawDesc), len(file_txproto_ripple_ripple_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_ripple_ripple_proto_goTypes,
		DependencyIndexes: file_txproto_ripple_ripple_proto_depIdxs,
		MessageInfos:      file_txproto_ripple_ripple_proto_msgTypes,
	}.Build()
	File_txproto_ripple_ripple_proto = out.File
	file_txproto_ripple_ripple_proto_goTypes = nil
	file_txproto_ripple_ripple_proto_depIdxs = nil
}
