// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/cosmos/cosmos.proto

package cosmos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A bank MsgSend.
type SendCoinsMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	FromAddress string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress   string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Single denom/amount pair (the common case).
	Amount        string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom         string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCoinsMessage) Reset() {
	*x = SendCoinsMessage{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCoinsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCoinsMessage) ProtoMessage() {}

func (x *SendCoinsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCoinsMessage.ProtoReflect.Descriptor instead.
func (*SendCoinsMessage) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{0}
}

func (x *SendCoinsMessage) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *SendCoinsMessage) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SendCoinsMessage) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendCoinsMessage) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

// A staking MsgDelegate / MsgUndelegate (identical wire shape; the type_url
// differs by which Message oneof field carries it).
type MsgDelegate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DelegatorAddress string                 `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	ValidatorAddress string                 `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	Amount           string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom            string                 `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgDelegate) Reset() {
	*x = MsgDelegate{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDelegate) ProtoMessage() {}

func (x *MsgDelegate) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDelegate.ProtoReflect.Descriptor instead.
func (*MsgDelegate) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{1}
}

func (x *MsgDelegate) GetDelegatorAddress() string {
	if x != nil {
		return x.DelegatorAddress
	}
	return ""
}

func (x *MsgDelegate) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *MsgDelegate) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgDelegate) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

// A distribution MsgWithdrawDelegatorReward.
type MsgWithdrawReward struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DelegatorAddress string                 `protobuf:"bytes,1,opt,name=delegator_address,json=delegatorAddress,proto3" json:"delegator_address,omitempty"`
	ValidatorAddress string                 `protobuf:"bytes,2,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MsgWithdrawReward) Reset() {
	*x = MsgWithdrawReward{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgWithdrawReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgWithdrawReward) ProtoMessage() {}

func (x *MsgWithdrawReward) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgWithdrawReward.ProtoReflect.Descriptor instead.
func (*MsgWithdrawReward) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{2}
}

func (x *MsgWithdrawReward) GetDelegatorAddress() string {
	if x != nil {
		return x.DelegatorAddress
	}
	return ""
}

func (x *MsgWithdrawReward) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

// One message in the transaction body. Multiple messages may be sent in one tx
// via SigningInput.messages.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageOneof:
	//
	//	*Message_Send
	//	*Message_Delegate
	//	*Message_Undelegate
	//	*Message_WithdrawReward
	MessageOneof  isMessage_MessageOneof `protobuf_oneof:"message_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetMessageOneof() isMessage_MessageOneof {
	if x != nil {
		return x.MessageOneof
	}
	return nil
}

func (x *Message) GetSend() *SendCoinsMessage {
	if x != nil {
		if x, ok := x.MessageOneof.(*Message_Send); ok {
			return x.Send
		}
	}
	return nil
}

func (x *Message) GetDelegate() *MsgDelegate {
	if x != nil {
		if x, ok := x.MessageOneof.(*Message_Delegate); ok {
			return x.Delegate
		}
	}
	return nil
}

func (x *Message) GetUndelegate() *MsgDelegate {
	if x != nil {
		if x, ok := x.MessageOneof.(*Message_Undelegate); ok {
			return x.Undelegate
		}
	}
	return nil
}

func (x *Message) GetWithdrawReward() *MsgWithdrawReward {
	if x != nil {
		if x, ok := x.MessageOneof.(*Message_WithdrawReward); ok {
			return x.WithdrawReward
		}
	}
	return nil
}

type isMessage_MessageOneof interface {
	isMessage_MessageOneof()
}

type Message_Send struct {
	Send *SendCoinsMessage `protobuf:"bytes,1,opt,name=send,proto3,oneof"`
}

type Message_Delegate struct {
	Delegate *MsgDelegate `protobuf:"bytes,2,opt,name=delegate,proto3,oneof"`
}

type Message_Undelegate struct {
	Undelegate *MsgDelegate `protobuf:"bytes,3,opt,name=undelegate,proto3,oneof"`
}

type Message_WithdrawReward struct {
	WithdrawReward *MsgWithdrawReward `protobuf:"bytes,4,opt,name=withdraw_reward,json=withdrawReward,proto3,oneof"`
}

func (*Message_Send) isMessage_MessageOneof() {}

func (*Message_Delegate) isMessage_MessageOneof() {}

func (*Message_Undelegate) isMessage_MessageOneof() {}

func (*Message_WithdrawReward) isMessage_MessageOneof() {}

// Fee for the transaction.
type Fee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"` // single coin amount
	Denom         string                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`   // single coin denom
	Gas           uint64                 `protobuf:"varint,3,opt,name=gas,proto3" json:"gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fee) Reset() {
	*x = Fee{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fee) ProtoMessage() {}

func (x *Fee) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fee.ProtoReflect.Descriptor instead.
func (*Fee) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{4}
}

func (x *Fee) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Fee) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Fee) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

// SigningInput mirrors a minimal subset of TW.Cosmos.Proto.SigningInput for
// DIRECT (protobuf) sign mode with a single bank MsgSend.
type SigningInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber uint64                 `protobuf:"varint,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Memo          string                 `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	Fee           *Fee                   `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	// Legacy single bank send (kept for back-compat). Prefer `messages`.
	Send *SendCoinsMessage `protobuf:"bytes,6,opt,name=send,proto3" json:"send,omitempty"`
	// One or more messages (bank send, staking delegate/undelegate, reward
	// withdrawal). When non-empty this takes precedence over `send`.
	Messages      []*Message `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{5}
}

func (x *SigningInput) GetAccountNumber() uint64 {
	if x != nil {
		return x.AccountNumber
	}
	return 0
}

func (x *SigningInput) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *SigningInput) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SigningInput) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *SigningInput) GetFee() *Fee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *SigningInput) GetSend() *SendCoinsMessage {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *SigningInput) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Cosmos.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protobuf-serialized TxRaw bytes.
	Encoded []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// base64 of `encoded`, as TWC reports it in `serialized` tx_bytes.
	TxBytes string `protobuf:"bytes,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	// 64-byte signature (R||S).
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// Error message, empty on success.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_cosmos_cosmos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_cosmos_cosmos_proto_rawDescGZIP(), []int{6}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetTxBytes() string {
	if x != nil {
		return x.TxBytes
	}
	return ""
}

func (x *SigningOutput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_cosmos_cosmos_proto protoreflect.FileDescriptor

const file_txproto_cosmos_cosmos_proto_rawDesc = "" +
	"\n" +
	"\x1btxproto/cosmos/cosmos.proto\x12\x15hdwallet.cosmos.proto\"\x82\x01\n" +
	"\x10SendCoinsMessage\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x04 \x01(\tR\x05denom\"\x95\x01\n" +
	"\vMsgDelegate\x12+\n" +
	"\x11delegator_address\x18\x01 \x01(\tR\x10delegatorAddress\x12+\n" +
	"\x11validator_address\x18\x02 \x01(\tR\x10validatorAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x04 \x01(\tR\x05denom\"m\n" +
	"\x11MsgWithdrawReward\x12+\n" +
	"\x11delegator_address\x18\x01 \x01(\tR\x10delegatorAddress\x12+\n" +
	"\x11validator_address\x18\x02 \x01(\tR\x10validatorAddress\"\xb6\x02\n" +
	"\aMessage\x12=\n" +
	"\x04send\x18\x01 \x01(\v2'.hdwallet.cosmos.proto.SendCoinsMessageH\x00R\x04send\x12@\n" +
	"\bdelegate\x18\x02 \x01(\v2\".hdwallet.cosmos.proto.MsgDelegateH\x00R\bdelegate\x12D\n" +
	"\n" +
	"undelegate\x18\x03 \x01(\v2\".hdwallet.cosmos.proto.MsgDelegateH\x00R\n" +
	"undelegate\x12S\n" +
	"\x0fwithdraw_reward\x18\x04 \x01(\v2(.hdwallet.cosmos.proto.MsgWithdrawRewardH\x00R\x0ewithdrawRewardB\x0f\n" +
	"\rmessage_oneof\"E\n" +
	"\x03Fee\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x14\n" +
	"\x05denom\x18\x02 \x01(\tR\x05denom\x12\x10\n" +
	"\x03gas\x18\x03 \x01(\x04R\x03gas\"\xa7\x02\n" +
	"\fSigningInput\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\x04R\raccountNumber\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04memo\x18\x04 \x01(\tR\x04memo\x12,\n" +
	"\x03fee\x18\x05 \x01(\v2\x1a.hdwallet.cosmos.proto.FeeR\x03fee\x12;\n" +
	"\x04send\x18\x06 \x01(\v2'.hdwallet.cosmos.proto.SendCoinsMessageR\x04send\x12:\n" +
	"\bmessages\x18\a \x03(\v2\x1e.hdwallet.cosmos.proto.MessageR\bmessages\"x\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\tR\atxBytes\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB1Z/github.com/ranjbar-dev/hd-wallet/txproto/cosmosb\x06proto3"

var (
	file_txproto_cosmos_cosmos_proto_rawDescOnce sync.Once
	file_txproto_cosmos_cosmos_proto_rawDescData []byte
)

func file_txproto_cosmos_cosmos_proto_rawDescGZIP() []byte {
	file_txproto_cosmos_cosmos_proto_rawDescOnce.Do(func() {
		file_txproto_cosmos_cosmos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_cosmos_cosmos_proto_rawDesc), len(file_txproto_cosmos_cosmos_proto_rawDesc)))
	})
	return file_txproto_cosmos_cosmos_proto_rawDescData
}

var file_txproto_cosmos_cosmos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_txproto_cosmos_cosmos_proto_goTypes = []any{
	(*SendCoinsMessage)(nil),  // 0: hdwallet.cosmos.proto.SendCoinsMessage
	(*MsgDelegate)(nil),       // 1: hdwallet.cosmos.proto.MsgDelegate
	(*MsgWithdrawReward)(nil), // 2: hdwallet.cosmos.proto.MsgWithdrawReward
	(*Message)(nil),           // 3: hdwallet.cosmos.proto.Message
	(*Fee)(nil),               // 4: hdwallet.cosmos.proto.Fee
	(*SigningInput)(nil),      // 5: hdwallet.cosmos.proto.SigningInput
	(*SigningOutput)(nil),     // 6: hdwallet.cosmos.proto.SigningOutput
}
var file_txproto_cosmos_cosmos_proto_depIdxs = []int32{
	0, // 0: hdwallet.cosmos.proto.Message.send:type_name -> hdwallet.cosmos.proto.SendCoinsMessage
	1, // 1: hdwallet.cosmos.proto.Message.delegate:type_name -> hdwallet.cosmos.proto.MsgDelegate
	1, // 2: hdwallet.cosmos.proto.Message.undelegate:type_name -> hdwallet.cosmos.proto.MsgDelegate
	2, // 3: hdwallet.cosmos.proto.Message.withdraw_reward:type_name -> hdwallet.cosmos.proto.MsgWithdrawReward
	4, // 4: hdwallet.cosmos.proto.SigningInput.fee:type_name -> hdwallet.cosmos.proto.Fee
	0, // 5: hdwallet.cosmos.proto.SigningInput.send:type_name -> hdwallet.cosmos.proto.SendCoinsMessage
	3, // 6: hdwallet.cosmos.proto.SigningInput.messages:type_name -> hdwallet.cosmos.proto.Message
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_txproto_cosmos_cosmos_proto_init() }
func file_txproto_cosmos_cosmos_proto_init() {
	if File_txproto_cosmos_cosmos_proto != nil {
		return
	}
	file_txproto_cosmos_cosmos_proto_msgTypes[3].OneofWrappers = []any{
		(*Message_Send)(nil),
		(*Message_Delegate)(nil),
		(*Message_Undelegate)(nil),
		(*Message_WithdrawReward)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_cosmos_cosmos_proto_rawDesc), len(file_txproto_cosmos_cosmos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_cosmos_cosmos_proto_goTypes,
		DependencyIndexes: file_txproto_cosmos_cosmos_proto_depIdxs,
		MessageInfos:      file_txproto_cosmos_cosmos_proto_msgTypes,
	}.Build()
	File_txproto_cosmos_cosmos_proto = out.File
	file_txproto_cosmos_cosmos_proto_goTypes = nil
	file_txproto_cosmos_cosmos_proto_depIdxs = nil
}
