// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/stellar/stellar.proto

package stellar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment operation: transfer native XLM.
type PaymentOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // G-address of the recipient
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`          // amount in stroops (1 XLM = 10_000_000 stroops)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOp) Reset() {
	*x = PaymentOp{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOp) ProtoMessage() {}

func (x *PaymentOp) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOp.ProtoReflect.Descriptor instead.
func (*PaymentOp) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentOp) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PaymentOp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Fund a not-yet-existing account (Stellar rejects Payment to unfunded accounts).
type CreateAccountOp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Destination     string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`                                 // G-address
	StartingBalance int64                  `protobuf:"varint,2,opt,name=starting_balance,json=startingBalance,proto3" json:"starting_balance,omitempty"` // stroops
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAccountOp) Reset() {
	*x = CreateAccountOp{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountOp) ProtoMessage() {}

func (x *CreateAccountOp) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountOp.ProtoReflect.Descriptor instead.
func (*CreateAccountOp) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountOp) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateAccountOp) GetStartingBalance() int64 {
	if x != nil {
		return x.StartingBalance
	}
	return 0
}

type MemoText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoText) Reset() {
	*x = MemoText{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoText) ProtoMessage() {}

func (x *MemoText) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoText.ProtoReflect.Descriptor instead.
func (*MemoText) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{2}
}

func (x *MemoText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MemoId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoId) Reset() {
	*x = MemoId{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoId) ProtoMessage() {}

func (x *MemoId) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoId.ProtoReflect.Descriptor instead.
func (*MemoId) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{3}
}

func (x *MemoId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MemoHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoHash) Reset() {
	*x = MemoHash{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoHash) ProtoMessage() {}

func (x *MemoHash) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoHash.ProtoReflect.Descriptor instead.
func (*MemoHash) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{4}
}

func (x *MemoHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// SigningInput mirrors a minimal subset of TW.Stellar.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source account G-address (needed for XDR source-account field).
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Base fee in stroops (per-operation); e.g. 1000.
	Fee int32 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	// Transaction sequence number (one more than the account's current seq).
	Sequence int64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Stellar network passphrase. Empty string → mainnet default:
	//
	//	"Public Global Stellar Network ; September 2015"
	Passphrase string `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*SigningInput_Payment
	//	*SigningInput_CreateAccount
	Operation isSigningInput_Operation `protobuf_oneof:"operation"`
	// Types that are valid to be assigned to Memo:
	//
	//	*SigningInput_MemoText
	//	*SigningInput_MemoId
	//	*SigningInput_MemoHash
	Memo          isSigningInput_Memo `protobuf_oneof:"memo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{5}
}

func (x *SigningInput) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SigningInput) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SigningInput) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SigningInput) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *SigningInput) GetOperation() isSigningInput_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SigningInput) GetPayment() *PaymentOp {
	if x != nil {
		if x, ok := x.Operation.(*SigningInput_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *SigningInput) GetCreateAccount() *CreateAccountOp {
	if x != nil {
		if x, ok := x.Operation.(*SigningInput_CreateAccount); ok {
			return x.CreateAccount
		}
	}
	return nil
}

func (x *SigningInput) GetMemo() isSigningInput_Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *SigningInput) GetMemoText() *MemoText {
	if x != nil {
		if x, ok := x.Memo.(*SigningInput_MemoText); ok {
			return x.MemoText
		}
	}
	return nil
}

func (x *SigningInput) GetMemoId() *MemoId {
	if x != nil {
		if x, ok := x.Memo.(*SigningInput_MemoId); ok {
			return x.MemoId
		}
	}
	return nil
}

func (x *SigningInput) GetMemoHash() *MemoHash {
	if x != nil {
		if x, ok := x.Memo.(*SigningInput_MemoHash); ok {
			return x.MemoHash
		}
	}
	return nil
}

type isSigningInput_Operation interface {
	isSigningInput_Operation()
}

type SigningInput_Payment struct {
	Payment *PaymentOp `protobuf:"bytes,5,opt,name=payment,proto3,oneof"`
}

type SigningInput_CreateAccount struct {
	CreateAccount *CreateAccountOp `protobuf:"bytes,9,opt,name=create_account,json=createAccount,proto3,oneof"`
}

func (*SigningInput_Payment) isSigningInput_Operation() {}

func (*SigningInput_CreateAccount) isSigningInput_Operation() {}

type isSigningInput_Memo interface {
	isSigningInput_Memo()
}

type SigningInput_MemoText struct {
	MemoText *MemoText `protobuf:"bytes,6,opt,name=memo_text,json=memoText,proto3,oneof"`
}

type SigningInput_MemoId struct {
	MemoId *MemoId `protobuf:"bytes,7,opt,name=memo_id,json=memoId,proto3,oneof"`
}

type SigningInput_MemoHash struct {
	MemoHash *MemoHash `protobuf:"bytes,8,opt,name=memo_hash,json=memoHash,proto3,oneof"`
}

func (*SigningInput_MemoText) isSigningInput_Memo() {}

func (*SigningInput_MemoId) isSigningInput_Memo() {}

func (*SigningInput_MemoHash) isSigningInput_Memo() {}

// SigningOutput mirrors a minimal subset of TW.Stellar.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base64(XDR(TransactionEnvelope)) — the wire-ready signed transaction.
	Encoded string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Raw XDR bytes of the TransactionEnvelope.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// Error message; empty on success.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{6}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_stellar_stellar_proto protoreflect.FileDescriptor

const file_txproto_stellar_stellar_proto_rawDesc = "" +
	"\n" +
	"\x1dtxproto/stellar/stellar.proto\x12\x16hdwallet.stellar.proto\"E\n" +
	"\tPaymentOp\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"^\n" +
	"\x0fCreateAccountOp\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12)\n" +
	"\x10starting_balance\x18\x02 \x01(\x03R\x0fstartingBalance\"\x1e\n" +
	"\bMemoText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x18\n" +
	"\x06MemoId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1e\n" +
	"\bMemoHash\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"\xd9\x03\n" +
	"\fSigningInput\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x05R\x03fee\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x04 \x01(\tR\n" +
	"passphrase\x12=\n" +
	"\apayment\x18\x05 \x01(\v2!.hdwallet.stellar.proto.PaymentOpH\x00R\apayment\x12P\n" +
	"\x0ecreate_account\x18\t \x01(\v2'.hdwallet.stellar.proto.CreateAccountOpH\x00R\rcreateAccount\x12?\n" +
	"\tmemo_text\x18\x06 \x01(\v2 .hdwallet.stellar.proto.MemoTextH\x01R\bmemoText\x129\n" +
	"\amemo_id\x18\a \x01(\v2\x1e.hdwallet.stellar.proto.MemoIdH\x01R\x06memoId\x12?\n" +
	"\tmemo_hash\x18\b \x01(\v2 .hdwallet.stellar.proto.MemoHashH\x01R\bmemoHashB\v\n" +
	"\toperationB\x06\n" +
	"\x04memo\"Q\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB2Z0github.com/ranjbar-dev/hd-wallet/txproto/stellarb\x06proto3"

var (
	file_txproto_stellar_stellar_proto_rawDescOnce sync.Once
	file_txproto_stellar_stellar_proto_rawDescData []byte
)

func file_txproto_stellar_stellar_proto_rawDescGZIP() []byte {
	file_txproto_stellar_stellar_proto_rawDescOnce.Do(func() {
		file_txproto_stellar_stellar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_stellar_stellar_proto_rawDesc), len(file_txproto_stellar_stellar_proto_rawDesc)))
	})
	return file_txproto_stellar_stellar_proto_rawDescData
}

var file_txproto_stellar_stellar_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_txproto_stellar_stellar_proto_goTypes = []any{
	(*PaymentOp)(nil),       // 0: hdwallet.stellar.proto.PaymentOp
	(*CreateAccountOp)(nil), // 1: hdwallet.stellar.proto.CreateAccountOp
	(*MemoText)(nil),        // 2: hdwallet.stellar.proto.MemoText
	(*MemoId)(nil),          // 3: hdwallet.stellar.proto.MemoId
	(*MemoHash)(nil),        // 4: hdwallet.stellar.proto.MemoHash
	(*SigningInput)(nil),    // 5: hdwallet.stellar.proto.SigningInput
	(*SigningOutput)(nil),   // 6: hdwallet.stellar.proto.SigningOutput
}
var file_txproto_stellar_stellar_proto_depIdxs = []int32{
	0, // 0: hdwallet.stellar.proto.SigningInput.payment:type_name -> hdwallet.stellar.proto.PaymentOp
	1, // 1: hdwallet.stellar.proto.SigningInput.create_account:type_name -> hdwallet.stellar.proto.CreateAccountOp
	2, // 2: hdwallet.stellar.proto.SigningInput.memo_text:type_name -> hdwallet.stellar.proto.MemoText
	3, // 3: hdwallet.stellar.proto.SigningInput.memo_id:type_name -> hdwallet.stellar.proto.MemoId
	4, // 4: hdwallet.stellar.proto.SigningInput.memo_hash:type_name -> hdwallet.stellar.proto.MemoHash
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_txproto_stellar_stellar_proto_init() }
func file_txproto_stellar_stellar_proto_init() {
	if File_txproto_stellar_stellar_proto != nil {
		return
	}
	file_txproto_stellar_stellar_proto_msgTypes[5].OneofWrappers = []any{
		(*SigningInput_Payment)(nil),
		(*SigningInput_CreateAccount)(nil),
		(*SigningInput_MemoText)(nil),
		(*SigningInput_MemoId)(nil),
		(*SigningInput_MemoHash)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_stellar_stellar_proto_rawDesc), len(file_txproto_stellar_stellar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_stellar_stellar_proto_goTypes,
		DependencyIndexes: file_txproto_stellar_stellar_proto_depIdxs,
		MessageInfos:      file_txproto_stellar_stellar_proto_msgTypes,
	}.Build()
	File_txproto_stellar_stellar_proto = out.File
	file_txproto_stellar_stellar_proto_goTypes = nil
	file_txproto_stellar_stellar_proto_depIdxs = nil
}
