// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/stellar/stellar.proto

package stellar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment operation: transfer native XLM.
type PaymentOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"` // G-address of the recipient
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`          // amount in stroops (1 XLM = 10_000_000 stroops)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentOp) Reset() {
	*x = PaymentOp{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOp) ProtoMessage() {}

func (x *PaymentOp) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOp.ProtoReflect.Descriptor instead.
func (*PaymentOp) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentOp) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PaymentOp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// SigningInput mirrors a minimal subset of TW.Stellar.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source account G-address (needed for XDR source-account field).
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Base fee in stroops (per-operation); e.g. 1000.
	Fee int32 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	// Transaction sequence number (one more than the account's current seq).
	Sequence int64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Stellar network passphrase. Empty string → mainnet default:
	//
	//	"Public Global Stellar Network ; September 2015"
	Passphrase string `protobuf:"bytes,4,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*SigningInput_Payment
	Operation     isSigningInput_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SigningInput) GetFee() int32 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *SigningInput) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SigningInput) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *SigningInput) GetOperation() isSigningInput_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SigningInput) GetPayment() *PaymentOp {
	if x != nil {
		if x, ok := x.Operation.(*SigningInput_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

type isSigningInput_Operation interface {
	isSigningInput_Operation()
}

type SigningInput_Payment struct {
	Payment *PaymentOp `protobuf:"bytes,5,opt,name=payment,proto3,oneof"`
}

func (*SigningInput_Payment) isSigningInput_Operation() {}

// SigningOutput mirrors a minimal subset of TW.Stellar.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base64(XDR(TransactionEnvelope)) — the wire-ready signed transaction.
	Encoded string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Raw XDR bytes of the TransactionEnvelope.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// Error message; empty on success.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_stellar_stellar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_stellar_stellar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_stellar_stellar_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_stellar_stellar_proto protoreflect.FileDescriptor

const file_txproto_stellar_stellar_proto_rawDesc = "" +
	"\n" +
	"\x1dtxproto/stellar/stellar.proto\x12\x16hdwallet.stellar.proto\"E\n" +
	"\tPaymentOp\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xc2\x01\n" +
	"\fSigningInput\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x05R\x03fee\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x04 \x01(\tR\n" +
	"passphrase\x12=\n" +
	"\apayment\x18\x05 \x01(\v2!.hdwallet.stellar.proto.PaymentOpH\x00R\apaymentB\v\n" +
	"\toperation\"Q\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB2Z0github.com/ranjbar-dev/hd-wallet/txproto/stellarb\x06proto3"

var (
	file_txproto_stellar_stellar_proto_rawDescOnce sync.Once
	file_txproto_stellar_stellar_proto_rawDescData []byte
)

func file_txproto_stellar_stellar_proto_rawDescGZIP() []byte {
	file_txproto_stellar_stellar_proto_rawDescOnce.Do(func() {
		file_txproto_stellar_stellar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_stellar_stellar_proto_rawDesc), len(file_txproto_stellar_stellar_proto_rawDesc)))
	})
	return file_txproto_stellar_stellar_proto_rawDescData
}

var file_txproto_stellar_stellar_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_txproto_stellar_stellar_proto_goTypes = []any{
	(*PaymentOp)(nil),     // 0: hdwallet.stellar.proto.PaymentOp
	(*SigningInput)(nil),  // 1: hdwallet.stellar.proto.SigningInput
	(*SigningOutput)(nil), // 2: hdwallet.stellar.proto.SigningOutput
}
var file_txproto_stellar_stellar_proto_depIdxs = []int32{
	0, // 0: hdwallet.stellar.proto.SigningInput.payment:type_name -> hdwallet.stellar.proto.PaymentOp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_txproto_stellar_stellar_proto_init() }
func file_txproto_stellar_stellar_proto_init() {
	if File_txproto_stellar_stellar_proto != nil {
		return
	}
	file_txproto_stellar_stellar_proto_msgTypes[1].OneofWrappers = []any{
		(*SigningInput_Payment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_stellar_stellar_proto_rawDesc), len(file_txproto_stellar_stellar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_stellar_stellar_proto_goTypes,
		DependencyIndexes: file_txproto_stellar_stellar_proto_depIdxs,
		MessageInfos:      file_txproto_stellar_stellar_proto_msgTypes,
	}.Build()
	File_txproto_stellar_stellar_proto = out.File
	file_txproto_stellar_stellar_proto_goTypes = nil
	file_txproto_stellar_stellar_proto_depIdxs = nil
}
