// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/solana/solana.proto

package solana

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Native SOL transfer via the System Program.
type Transfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipient     string                 `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"` // base58 address
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`        // lamports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_txproto_solana_solana_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_solana_solana_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_solana_solana_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *Transfer) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// SPL token transfer via the Token Program (checked transfer).
type TokenTransfer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TokenMintAddress      string                 `protobuf:"bytes,1,opt,name=token_mint_address,json=tokenMintAddress,proto3" json:"token_mint_address,omitempty"`                // base58
	SenderTokenAddress    string                 `protobuf:"bytes,2,opt,name=sender_token_address,json=senderTokenAddress,proto3" json:"sender_token_address,omitempty"`          // base58 (the source ATA)
	RecipientTokenAddress string                 `protobuf:"bytes,3,opt,name=recipient_token_address,json=recipientTokenAddress,proto3" json:"recipient_token_address,omitempty"` // base58 (the destination ATA)
	Amount                uint64                 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Decimals              uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TokenTransfer) Reset() {
	*x = TokenTransfer{}
	mi := &file_txproto_solana_solana_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransfer) ProtoMessage() {}

func (x *TokenTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_solana_solana_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransfer.ProtoReflect.Descriptor instead.
func (*TokenTransfer) Descriptor() ([]byte, []int) {
	return file_txproto_solana_solana_proto_rawDescGZIP(), []int{1}
}

func (x *TokenTransfer) GetTokenMintAddress() string {
	if x != nil {
		return x.TokenMintAddress
	}
	return ""
}

func (x *TokenTransfer) GetSenderTokenAddress() string {
	if x != nil {
		return x.SenderTokenAddress
	}
	return ""
}

func (x *TokenTransfer) GetRecipientTokenAddress() string {
	if x != nil {
		return x.RecipientTokenAddress
	}
	return ""
}

func (x *TokenTransfer) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TokenTransfer) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// SigningInput mirrors a minimal subset of TW.Solana.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recent blockhash, base58.
	RecentBlockhash string `protobuf:"bytes,1,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"`
	// Types that are valid to be assigned to TransactionType:
	//
	//	*SigningInput_TransferTransaction
	//	*SigningInput_TokenTransferTransaction
	TransactionType isSigningInput_TransactionType `protobuf_oneof:"transaction_type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_solana_solana_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_solana_solana_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_solana_solana_proto_rawDescGZIP(), []int{2}
}

func (x *SigningInput) GetRecentBlockhash() string {
	if x != nil {
		return x.RecentBlockhash
	}
	return ""
}

func (x *SigningInput) GetTransactionType() isSigningInput_TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *SigningInput) GetTransferTransaction() *Transfer {
	if x != nil {
		if x, ok := x.TransactionType.(*SigningInput_TransferTransaction); ok {
			return x.TransferTransaction
		}
	}
	return nil
}

func (x *SigningInput) GetTokenTransferTransaction() *TokenTransfer {
	if x != nil {
		if x, ok := x.TransactionType.(*SigningInput_TokenTransferTransaction); ok {
			return x.TokenTransferTransaction
		}
	}
	return nil
}

type isSigningInput_TransactionType interface {
	isSigningInput_TransactionType()
}

type SigningInput_TransferTransaction struct {
	TransferTransaction *Transfer `protobuf:"bytes,2,opt,name=transfer_transaction,json=transferTransaction,proto3,oneof"`
}

type SigningInput_TokenTransferTransaction struct {
	TokenTransferTransaction *TokenTransfer `protobuf:"bytes,3,opt,name=token_transfer_transaction,json=tokenTransferTransaction,proto3,oneof"`
}

func (*SigningInput_TransferTransaction) isSigningInput_TransactionType() {}

func (*SigningInput_TokenTransferTransaction) isSigningInput_TransactionType() {}

// SigningOutput mirrors a minimal subset of TW.Solana.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base58 of the fully signed transaction.
	Encoded string `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// raw signed transaction bytes.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	// Error message, empty on success.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_solana_solana_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_solana_solana_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_solana_solana_proto_rawDescGZIP(), []int{3}
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_solana_solana_proto protoreflect.FileDescriptor

const file_txproto_solana_solana_proto_rawDesc = "" +
	"\n" +
	"\x1btxproto/solana/solana.proto\x12\x15hdwallet.solana.proto\">\n" +
	"\bTransfer\x12\x1c\n" +
	"\trecipient\x18\x01 \x01(\tR\trecipient\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"\xdb\x01\n" +
	"\rTokenTransfer\x12,\n" +
	"\x12token_mint_address\x18\x01 \x01(\tR\x10tokenMintAddress\x120\n" +
	"\x14sender_token_address\x18\x02 \x01(\tR\x12senderTokenAddress\x126\n" +
	"\x17recipient_token_address\x18\x03 \x01(\tR\x15recipientTokenAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\"\x89\x02\n" +
	"\fSigningInput\x12)\n" +
	"\x10recent_blockhash\x18\x01 \x01(\tR\x0frecentBlockhash\x12T\n" +
	"\x14transfer_transaction\x18\x02 \x01(\v2\x1f.hdwallet.solana.proto.TransferH\x00R\x13transferTransaction\x12d\n" +
	"\x1atoken_transfer_transaction\x18\x03 \x01(\v2$.hdwallet.solana.proto.TokenTransferH\x00R\x18tokenTransferTransactionB\x12\n" +
	"\x10transaction_type\"Q\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\tR\aencoded\x12\x10\n" +
	"\x03raw\x18\x02 \x01(\fR\x03raw\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB1Z/github.com/ranjbar-dev/hd-wallet/txproto/solanab\x06proto3"

var (
	file_txproto_solana_solana_proto_rawDescOnce sync.Once
	file_txproto_solana_solana_proto_rawDescData []byte
)

func file_txproto_solana_solana_proto_rawDescGZIP() []byte {
	file_txproto_solana_solana_proto_rawDescOnce.Do(func() {
		file_txproto_solana_solana_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_solana_solana_proto_rawDesc), len(file_txproto_solana_solana_proto_rawDesc)))
	})
	return file_txproto_solana_solana_proto_rawDescData
}

var file_txproto_solana_solana_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_txproto_solana_solana_proto_goTypes = []any{
	(*Transfer)(nil),      // 0: hdwallet.solana.proto.Transfer
	(*TokenTransfer)(nil), // 1: hdwallet.solana.proto.TokenTransfer
	(*SigningInput)(nil),  // 2: hdwallet.solana.proto.SigningInput
	(*SigningOutput)(nil), // 3: hdwallet.solana.proto.SigningOutput
}
var file_txproto_solana_solana_proto_depIdxs = []int32{
	0, // 0: hdwallet.solana.proto.SigningInput.transfer_transaction:type_name -> hdwallet.solana.proto.Transfer
	1, // 1: hdwallet.solana.proto.SigningInput.token_transfer_transaction:type_name -> hdwallet.solana.proto.TokenTransfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_txproto_solana_solana_proto_init() }
func file_txproto_solana_solana_proto_init() {
	if File_txproto_solana_solana_proto != nil {
		return
	}
	file_txproto_solana_solana_proto_msgTypes[2].OneofWrappers = []any{
		(*SigningInput_TransferTransaction)(nil),
		(*SigningInput_TokenTransferTransaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_solana_solana_proto_rawDesc), len(file_txproto_solana_solana_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_solana_solana_proto_goTypes,
		DependencyIndexes: file_txproto_solana_solana_proto_depIdxs,
		MessageInfos:      file_txproto_solana_solana_proto_msgTypes,
	}.Build()
	File_txproto_solana_solana_proto = out.File
	file_txproto_solana_solana_proto_goTypes = nil
	file_txproto_solana_solana_proto_depIdxs = nil
}
