// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/ethereum/ethereum.proto

package ethereum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction type / payload. Mirrors a minimal subset of Trust Wallet Core's
// TW.Ethereum.Proto.Transaction.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TransactionOneof:
	//
	//	*Transaction_Transfer_
	//	*Transaction_Erc20Transfer
	TransactionOneof isTransaction_TransactionOneof `protobuf_oneof:"transaction_oneof"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTransactionOneof() isTransaction_TransactionOneof {
	if x != nil {
		return x.TransactionOneof
	}
	return nil
}

func (x *Transaction) GetTransfer() *Transaction_Transfer {
	if x != nil {
		if x, ok := x.TransactionOneof.(*Transaction_Transfer_); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *Transaction) GetErc20Transfer() *Transaction_ERC20Transfer {
	if x != nil {
		if x, ok := x.TransactionOneof.(*Transaction_Erc20Transfer); ok {
			return x.Erc20Transfer
		}
	}
	return nil
}

type isTransaction_TransactionOneof interface {
	isTransaction_TransactionOneof()
}

type Transaction_Transfer_ struct {
	Transfer *Transaction_Transfer `protobuf:"bytes,1,opt,name=transfer,proto3,oneof"`
}

type Transaction_Erc20Transfer struct {
	Erc20Transfer *Transaction_ERC20Transfer `protobuf:"bytes,2,opt,name=erc20_transfer,json=erc20Transfer,proto3,oneof"`
}

func (*Transaction_Transfer_) isTransaction_TransactionOneof() {}

func (*Transaction_Erc20Transfer) isTransaction_TransactionOneof() {}

// SigningInput mirrors a minimal subset of TW.Ethereum.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chain id, big-endian bytes (EIP-155).
	ChainId []byte `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Sender nonce, big-endian bytes.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Transaction type: 0 = legacy, 2 = EIP-1559 (type-2).
	TxMode uint32 `protobuf:"varint,3,opt,name=tx_mode,json=txMode,proto3" json:"tx_mode,omitempty"`
	// Legacy gas price, big-endian bytes (tx_mode == 0).
	GasPrice []byte `protobuf:"bytes,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Gas limit, big-endian bytes.
	GasLimit []byte `protobuf:"bytes,5,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// EIP-1559 max inclusion (priority) fee per gas, big-endian bytes.
	MaxInclusionFeePerGas []byte `protobuf:"bytes,6,opt,name=max_inclusion_fee_per_gas,json=maxInclusionFeePerGas,proto3" json:"max_inclusion_fee_per_gas,omitempty"`
	// EIP-1559 max fee per gas, big-endian bytes.
	MaxFeePerGas []byte `protobuf:"bytes,7,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	// Destination: recipient address for native transfer, or token contract
	// address for ERC-20 transfer ("0x"-prefixed hex).
	ToAddress string `protobuf:"bytes,8,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// What to do.
	Transaction   *Transaction `protobuf:"bytes,9,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{1}
}

func (x *SigningInput) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SigningInput) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SigningInput) GetTxMode() uint32 {
	if x != nil {
		return x.TxMode
	}
	return 0
}

func (x *SigningInput) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *SigningInput) GetGasLimit() []byte {
	if x != nil {
		return x.GasLimit
	}
	return nil
}

func (x *SigningInput) GetMaxInclusionFeePerGas() []byte {
	if x != nil {
		return x.MaxInclusionFeePerGas
	}
	return nil
}

func (x *SigningInput) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *SigningInput) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SigningInput) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Ethereum.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RLP-encoded signed transaction, ready to broadcast.
	Encoded []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Signature scalars and recovery value.
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	V []byte `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	// Hex of `encoded` (no "0x" prefix), for convenience.
	EncodedHex string `protobuf:"bytes,5,opt,name=encoded_hex,json=encodedHex,proto3" json:"encoded_hex,omitempty"`
	// Error message, empty on success.
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{2}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SigningOutput) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *SigningOutput) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *SigningOutput) GetEncodedHex() string {
	if x != nil {
		return x.EncodedHex
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Native coin transfer.
type Transaction_Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount to send, big-endian uint256 bytes.
	Amount []byte `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional contract-call payload appended after the value transfer.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Transfer) Reset() {
	*x = Transaction_Transfer{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Transfer) ProtoMessage() {}

func (x *Transaction_Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Transfer.ProtoReflect.Descriptor instead.
func (*Transaction_Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_Transfer) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction_Transfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ERC-20 token transfer.
type Transaction_ERC20Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient address ("0x"-prefixed hex).
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Token amount, big-endian uint256 bytes.
	Amount        []byte `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ERC20Transfer) Reset() {
	*x = Transaction_ERC20Transfer{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ERC20Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ERC20Transfer) ProtoMessage() {}

func (x *Transaction_ERC20Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ERC20Transfer.ProtoReflect.Descriptor instead.
func (*Transaction_ERC20Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Transaction_ERC20Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction_ERC20Transfer) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_txproto_ethereum_ethereum_proto protoreflect.FileDescriptor

const file_txproto_ethereum_ethereum_proto_rawDesc = "" +
	"\n" +
	"\x1ftxproto/ethereum/ethereum.proto\x12\x17hdwallet.ethereum.proto\"\xbd\x02\n" +
	"\vTransaction\x12K\n" +
	"\btransfer\x18\x01 \x01(\v2-.hdwallet.ethereum.proto.Transaction.TransferH\x00R\btransfer\x12[\n" +
	"\x0eerc20_transfer\x18\x02 \x01(\v22.hdwallet.ethereum.proto.Transaction.ERC20TransferH\x00R\rerc20Transfer\x1a6\n" +
	"\bTransfer\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\fR\x06amount\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a7\n" +
	"\rERC20Transfer\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\fR\x06amountB\x13\n" +
	"\x11transaction_oneof\"\xda\x02\n" +
	"\fSigningInput\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x17\n" +
	"\atx_mode\x18\x03 \x01(\rR\x06txMode\x12\x1b\n" +
	"\tgas_price\x18\x04 \x01(\fR\bgasPrice\x12\x1b\n" +
	"\tgas_limit\x18\x05 \x01(\fR\bgasLimit\x128\n" +
	"\x19max_inclusion_fee_per_gas\x18\x06 \x01(\fR\x15maxInclusionFeePerGas\x12%\n" +
	"\x0fmax_fee_per_gas\x18\a \x01(\fR\fmaxFeePerGas\x12\x1d\n" +
	"\n" +
	"to_address\x18\b \x01(\tR\ttoAddress\x12F\n" +
	"\vtransaction\x18\t \x01(\v2$.hdwallet.ethereum.proto.TransactionR\vtransaction\"\x8a\x01\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\f\n" +
	"\x01r\x18\x02 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x03 \x01(\fR\x01s\x12\f\n" +
	"\x01v\x18\x04 \x01(\fR\x01v\x12\x1f\n" +
	"\vencoded_hex\x18\x05 \x01(\tR\n" +
	"encodedHex\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB3Z1github.com/ranjbar-dev/hd-wallet/txproto/ethereumb\x06proto3"

var (
	file_txproto_ethereum_ethereum_proto_rawDescOnce sync.Once
	file_txproto_ethereum_ethereum_proto_rawDescData []byte
)

func file_txproto_ethereum_ethereum_proto_rawDescGZIP() []byte {
	file_txproto_ethereum_ethereum_proto_rawDescOnce.Do(func() {
		file_txproto_ethereum_ethereum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_ethereum_ethereum_proto_rawDesc), len(file_txproto_ethereum_ethereum_proto_rawDesc)))
	})
	return file_txproto_ethereum_ethereum_proto_rawDescData
}

var file_txproto_ethereum_ethereum_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_txproto_ethereum_ethereum_proto_goTypes = []any{
	(*Transaction)(nil),               // 0: hdwallet.ethereum.proto.Transaction
	(*SigningInput)(nil),              // 1: hdwallet.ethereum.proto.SigningInput
	(*SigningOutput)(nil),             // 2: hdwallet.ethereum.proto.SigningOutput
	(*Transaction_Transfer)(nil),      // 3: hdwallet.ethereum.proto.Transaction.Transfer
	(*Transaction_ERC20Transfer)(nil), // 4: hdwallet.ethereum.proto.Transaction.ERC20Transfer
}
var file_txproto_ethereum_ethereum_proto_depIdxs = []int32{
	3, // 0: hdwallet.ethereum.proto.Transaction.transfer:type_name -> hdwallet.ethereum.proto.Transaction.Transfer
	4, // 1: hdwallet.ethereum.proto.Transaction.erc20_transfer:type_name -> hdwallet.ethereum.proto.Transaction.ERC20Transfer
	0, // 2: hdwallet.ethereum.proto.SigningInput.transaction:type_name -> hdwallet.ethereum.proto.Transaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_txproto_ethereum_ethereum_proto_init() }
func file_txproto_ethereum_ethereum_proto_init() {
	if File_txproto_ethereum_ethereum_proto != nil {
		return
	}
	file_txproto_ethereum_ethereum_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_Transfer_)(nil),
		(*Transaction_Erc20Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_ethereum_ethereum_proto_rawDesc), len(file_txproto_ethereum_ethereum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_ethereum_ethereum_proto_goTypes,
		DependencyIndexes: file_txproto_ethereum_ethereum_proto_depIdxs,
		MessageInfos:      file_txproto_ethereum_ethereum_proto_msgTypes,
	}.Build()
	File_txproto_ethereum_ethereum_proto = out.File
	file_txproto_ethereum_ethereum_proto_goTypes = nil
	file_txproto_ethereum_ethereum_proto_depIdxs = nil
}
