// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/ethereum/ethereum.proto

package ethereum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction type / payload. Mirrors a minimal subset of Trust Wallet Core's
// TW.Ethereum.Proto.Transaction.
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TransactionOneof:
	//
	//	*Transaction_Transfer_
	//	*Transaction_Erc20Transfer
	//	*Transaction_ContractGeneric_
	TransactionOneof isTransaction_TransactionOneof `protobuf_oneof:"transaction_oneof"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTransactionOneof() isTransaction_TransactionOneof {
	if x != nil {
		return x.TransactionOneof
	}
	return nil
}

func (x *Transaction) GetTransfer() *Transaction_Transfer {
	if x != nil {
		if x, ok := x.TransactionOneof.(*Transaction_Transfer_); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *Transaction) GetErc20Transfer() *Transaction_ERC20Transfer {
	if x != nil {
		if x, ok := x.TransactionOneof.(*Transaction_Erc20Transfer); ok {
			return x.Erc20Transfer
		}
	}
	return nil
}

func (x *Transaction) GetContractGeneric() *Transaction_ContractGeneric {
	if x != nil {
		if x, ok := x.TransactionOneof.(*Transaction_ContractGeneric_); ok {
			return x.ContractGeneric
		}
	}
	return nil
}

type isTransaction_TransactionOneof interface {
	isTransaction_TransactionOneof()
}

type Transaction_Transfer_ struct {
	Transfer *Transaction_Transfer `protobuf:"bytes,1,opt,name=transfer,proto3,oneof"`
}

type Transaction_Erc20Transfer struct {
	Erc20Transfer *Transaction_ERC20Transfer `protobuf:"bytes,2,opt,name=erc20_transfer,json=erc20Transfer,proto3,oneof"`
}

type Transaction_ContractGeneric_ struct {
	ContractGeneric *Transaction_ContractGeneric `protobuf:"bytes,3,opt,name=contract_generic,json=contractGeneric,proto3,oneof"`
}

func (*Transaction_Transfer_) isTransaction_TransactionOneof() {}

func (*Transaction_Erc20Transfer) isTransaction_TransactionOneof() {}

func (*Transaction_ContractGeneric_) isTransaction_TransactionOneof() {}

// Access is one EIP-2930 access-list entry: an address plus the storage slots
// the transaction intends to access under it.
type Access struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address being accessed ("0x"-prefixed hex, 20 bytes).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Storage slots accessed under address; each is a 32-byte big-endian key.
	StoredKeys    [][]byte `protobuf:"bytes,2,rep,name=stored_keys,json=storedKeys,proto3" json:"stored_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Access) Reset() {
	*x = Access{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Access) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Access) ProtoMessage() {}

func (x *Access) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Access.ProtoReflect.Descriptor instead.
func (*Access) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{1}
}

func (x *Access) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Access) GetStoredKeys() [][]byte {
	if x != nil {
		return x.StoredKeys
	}
	return nil
}

// EthAuthorization is one EIP-7702 authorization-list entry. The EOA that
// wants to delegate its code to `address` signs [chain_id, address, nonce]
// off-band (using keccak256(0x05 || rlp([chain_id, address, nonce]))), and
// the resulting (y_parity, r, s) plus the delegation target are carried here.
// All fields are required; the tx signer does NOT sign the authorization tuple.
type EthAuthorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chain id for which this authorization is valid, big-endian bytes.
	ChainId []byte `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Delegation target ("0x"-prefixed hex, 20 bytes).
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Authorizing EOA nonce at the time of authorization.
	Nonce uint64 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// y_parity of the authorization signature (0 or 1).
	YParity uint32 `protobuf:"varint,4,opt,name=y_parity,json=yParity,proto3" json:"y_parity,omitempty"`
	// r component of the authorization signature, 32 bytes big-endian.
	R []byte `protobuf:"bytes,5,opt,name=r,proto3" json:"r,omitempty"`
	// s component of the authorization signature, 32 bytes big-endian.
	S             []byte `protobuf:"bytes,6,opt,name=s,proto3" json:"s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EthAuthorization) Reset() {
	*x = EthAuthorization{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EthAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthAuthorization) ProtoMessage() {}

func (x *EthAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthAuthorization.ProtoReflect.Descriptor instead.
func (*EthAuthorization) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{2}
}

func (x *EthAuthorization) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *EthAuthorization) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *EthAuthorization) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *EthAuthorization) GetYParity() uint32 {
	if x != nil {
		return x.YParity
	}
	return 0
}

func (x *EthAuthorization) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *EthAuthorization) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

// SigningInput mirrors a minimal subset of TW.Ethereum.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chain id, big-endian bytes (EIP-155).
	ChainId []byte `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Sender nonce, big-endian bytes.
	Nonce []byte `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Transaction type: 0 = legacy, 1 = EIP-2930 (access list), 2 = EIP-1559,
	// 3 = EIP-4844 (blob), 4 = EIP-7702 (set-code).
	TxMode uint32 `protobuf:"varint,3,opt,name=tx_mode,json=txMode,proto3" json:"tx_mode,omitempty"`
	// Legacy gas price, big-endian bytes (tx_mode == 0).
	GasPrice []byte `protobuf:"bytes,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Gas limit, big-endian bytes.
	GasLimit []byte `protobuf:"bytes,5,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// EIP-1559 max inclusion (priority) fee per gas, big-endian bytes.
	MaxInclusionFeePerGas []byte `protobuf:"bytes,6,opt,name=max_inclusion_fee_per_gas,json=maxInclusionFeePerGas,proto3" json:"max_inclusion_fee_per_gas,omitempty"`
	// EIP-1559 max fee per gas, big-endian bytes.
	MaxFeePerGas []byte `protobuf:"bytes,7,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	// Destination: recipient address for native transfer, or token contract
	// address for ERC-20 transfer ("0x"-prefixed hex).
	ToAddress string `protobuf:"bytes,8,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// What to do.
	Transaction *Transaction `protobuf:"bytes,9,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// Optional EIP-2930 access list. Carried in the signed bytes for tx_mode 1
	// (EIP-2930) and tx_mode 2 (EIP-1559); ignored for legacy (tx_mode 0). An
	// empty list reproduces the no-access-list encoding exactly.
	AccessList []*Access `protobuf:"bytes,10,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	// EIP-4844: max fee per blob gas (a.k.a. maxFeePerBlobGas), big-endian
	// bytes. Required for tx_mode 3 (EIP-4844); ignored otherwise.
	MaxFeePerBlobGas []byte `protobuf:"bytes,11,opt,name=max_fee_per_blob_gas,json=maxFeePerBlobGas,proto3" json:"max_fee_per_blob_gas,omitempty"`
	// EIP-4844: versioned blob hashes. Each entry must be exactly 32 bytes;
	// the first byte is the version (0x01 for KZG commitments per EIP-4844).
	// At least one hash is required for tx_mode 3; ignored otherwise.
	// The network-wrapper (blobs, commitments, proofs) is out of scope — only
	// the tx envelope is signed here.
	BlobVersionedHashes [][]byte `protobuf:"bytes,12,rep,name=blob_versioned_hashes,json=blobVersionedHashes,proto3" json:"blob_versioned_hashes,omitempty"`
	// EIP-7702: authorization list. Required for tx_mode 4 (EIP-7702); ignored
	// otherwise. Each entry is a pre-signed delegation authorization from an EOA
	// that wishes to set its code to point at a contract address.
	AuthorizationList []*EthAuthorization `protobuf:"bytes,13,rep,name=authorization_list,json=authorizationList,proto3" json:"authorization_list,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{3}
}

func (x *SigningInput) GetChainId() []byte {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *SigningInput) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SigningInput) GetTxMode() uint32 {
	if x != nil {
		return x.TxMode
	}
	return 0
}

func (x *SigningInput) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *SigningInput) GetGasLimit() []byte {
	if x != nil {
		return x.GasLimit
	}
	return nil
}

func (x *SigningInput) GetMaxInclusionFeePerGas() []byte {
	if x != nil {
		return x.MaxInclusionFeePerGas
	}
	return nil
}

func (x *SigningInput) GetMaxFeePerGas() []byte {
	if x != nil {
		return x.MaxFeePerGas
	}
	return nil
}

func (x *SigningInput) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *SigningInput) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SigningInput) GetAccessList() []*Access {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *SigningInput) GetMaxFeePerBlobGas() []byte {
	if x != nil {
		return x.MaxFeePerBlobGas
	}
	return nil
}

func (x *SigningInput) GetBlobVersionedHashes() [][]byte {
	if x != nil {
		return x.BlobVersionedHashes
	}
	return nil
}

func (x *SigningInput) GetAuthorizationList() []*EthAuthorization {
	if x != nil {
		return x.AuthorizationList
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Ethereum.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RLP-encoded signed transaction, ready to broadcast.
	Encoded []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Signature scalars and recovery value.
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	V []byte `protobuf:"bytes,4,opt,name=v,proto3" json:"v,omitempty"`
	// Hex of `encoded` (no "0x" prefix), for convenience.
	EncodedHex string `protobuf:"bytes,5,opt,name=encoded_hex,json=encodedHex,proto3" json:"encoded_hex,omitempty"`
	// Error message, empty on success.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Transaction id/hash: "0x" + lower-case hex of keccak256(encoded). This is
	// the canonical Ethereum tx hash explorers display and broadcast tracks.
	TxId          string `protobuf:"bytes,7,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{4}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SigningOutput) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *SigningOutput) GetV() []byte {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *SigningOutput) GetEncodedHex() string {
	if x != nil {
		return x.EncodedHex
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SigningOutput) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// Native coin transfer.
type Transaction_Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount to send, big-endian uint256 bytes.
	Amount []byte `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Optional contract-call payload appended after the value transfer.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_Transfer) Reset() {
	*x = Transaction_Transfer{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_Transfer) ProtoMessage() {}

func (x *Transaction_Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_Transfer.ProtoReflect.Descriptor instead.
func (*Transaction_Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Transaction_Transfer) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction_Transfer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ERC-20 token transfer.
type Transaction_ERC20Transfer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient address ("0x"-prefixed hex).
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Token amount, big-endian uint256 bytes.
	Amount        []byte `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ERC20Transfer) Reset() {
	*x = Transaction_ERC20Transfer{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ERC20Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ERC20Transfer) ProtoMessage() {}

func (x *Transaction_ERC20Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ERC20Transfer.ProtoReflect.Descriptor instead.
func (*Transaction_ERC20Transfer) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Transaction_ERC20Transfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction_ERC20Transfer) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

// Arbitrary contract call, or contract creation (deploy). For a call, set
// SigningInput.to_address to the contract address and put the call's ABI
// calldata in `data`. For creation, leave SigningInput.to_address empty and
// put the init code in `data`. `amount` is the native value to send (may be
// empty for zero).
type Transaction_ContractGeneric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Native value to send, big-endian uint256 bytes (empty == 0).
	Amount []byte `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Calldata (contract call) or init code (contract creation).
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction_ContractGeneric) Reset() {
	*x = Transaction_ContractGeneric{}
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction_ContractGeneric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction_ContractGeneric) ProtoMessage() {}

func (x *Transaction_ContractGeneric) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_ethereum_ethereum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction_ContractGeneric.ProtoReflect.Descriptor instead.
func (*Transaction_ContractGeneric) Descriptor() ([]byte, []int) {
	return file_txproto_ethereum_ethereum_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Transaction_ContractGeneric) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction_ContractGeneric) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_txproto_ethereum_ethereum_proto protoreflect.FileDescriptor

const file_txproto_ethereum_ethereum_proto_rawDesc = "" +
	"\n" +
	"\x1ftxproto/ethereum/ethereum.proto\x12\x17hdwallet.ethereum.proto\"\xdf\x03\n" +
	"\vTransaction\x12K\n" +
	"\btransfer\x18\x01 \x01(\v2-.hdwallet.ethereum.proto.Transaction.TransferH\x00R\btransfer\x12[\n" +
	"\x0eerc20_transfer\x18\x02 \x01(\v22.hdwallet.ethereum.proto.Transaction.ERC20TransferH\x00R\rerc20Transfer\x12a\n" +
	"\x10contract_generic\x18\x03 \x01(\v24.hdwallet.ethereum.proto.Transaction.ContractGenericH\x00R\x0fcontractGeneric\x1a6\n" +
	"\bTransfer\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\fR\x06amount\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a7\n" +
	"\rERC20Transfer\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\fR\x06amount\x1a=\n" +
	"\x0fContractGeneric\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\fR\x06amount\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04dataB\x13\n" +
	"\x11transaction_oneof\"C\n" +
	"\x06Access\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vstored_keys\x18\x02 \x03(\fR\n" +
	"storedKeys\"\x94\x01\n" +
	"\x10EthAuthorization\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12\x19\n" +
	"\by_parity\x18\x04 \x01(\rR\ayParity\x12\f\n" +
	"\x01r\x18\x05 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x06 \x01(\fR\x01s\"\xda\x04\n" +
	"\fSigningInput\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\fR\achainId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x17\n" +
	"\atx_mode\x18\x03 \x01(\rR\x06txMode\x12\x1b\n" +
	"\tgas_price\x18\x04 \x01(\fR\bgasPrice\x12\x1b\n" +
	"\tgas_limit\x18\x05 \x01(\fR\bgasLimit\x128\n" +
	"\x19max_inclusion_fee_per_gas\x18\x06 \x01(\fR\x15maxInclusionFeePerGas\x12%\n" +
	"\x0fmax_fee_per_gas\x18\a \x01(\fR\fmaxFeePerGas\x12\x1d\n" +
	"\n" +
	"to_address\x18\b \x01(\tR\ttoAddress\x12F\n" +
	"\vtransaction\x18\t \x01(\v2$.hdwallet.ethereum.proto.TransactionR\vtransaction\x12@\n" +
	"\vaccess_list\x18\n" +
	" \x03(\v2\x1f.hdwallet.ethereum.proto.AccessR\n" +
	"accessList\x12.\n" +
	"\x14max_fee_per_blob_gas\x18\v \x01(\fR\x10maxFeePerBlobGas\x122\n" +
	"\x15blob_versioned_hashes\x18\f \x03(\fR\x13blobVersionedHashes\x12X\n" +
	"\x12authorization_list\x18\r \x03(\v2).hdwallet.ethereum.proto.EthAuthorizationR\x11authorizationList\"\x9f\x01\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\f\n" +
	"\x01r\x18\x02 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x03 \x01(\fR\x01s\x12\f\n" +
	"\x01v\x18\x04 \x01(\fR\x01v\x12\x1f\n" +
	"\vencoded_hex\x18\x05 \x01(\tR\n" +
	"encodedHex\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x13\n" +
	"\x05tx_id\x18\a \x01(\tR\x04txIdB3Z1github.com/ranjbar-dev/hd-wallet/txproto/ethereumb\x06proto3"

var (
	file_txproto_ethereum_ethereum_proto_rawDescOnce sync.Once
	file_txproto_ethereum_ethereum_proto_rawDescData []byte
)

func file_txproto_ethereum_ethereum_proto_rawDescGZIP() []byte {
	file_txproto_ethereum_ethereum_proto_rawDescOnce.Do(func() {
		file_txproto_ethereum_ethereum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_ethereum_ethereum_proto_rawDesc), len(file_txproto_ethereum_ethereum_proto_rawDesc)))
	})
	return file_txproto_ethereum_ethereum_proto_rawDescData
}

var file_txproto_ethereum_ethereum_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_txproto_ethereum_ethereum_proto_goTypes = []any{
	(*Transaction)(nil),                 // 0: hdwallet.ethereum.proto.Transaction
	(*Access)(nil),                      // 1: hdwallet.ethereum.proto.Access
	(*EthAuthorization)(nil),            // 2: hdwallet.ethereum.proto.EthAuthorization
	(*SigningInput)(nil),                // 3: hdwallet.ethereum.proto.SigningInput
	(*SigningOutput)(nil),               // 4: hdwallet.ethereum.proto.SigningOutput
	(*Transaction_Transfer)(nil),        // 5: hdwallet.ethereum.proto.Transaction.Transfer
	(*Transaction_ERC20Transfer)(nil),   // 6: hdwallet.ethereum.proto.Transaction.ERC20Transfer
	(*Transaction_ContractGeneric)(nil), // 7: hdwallet.ethereum.proto.Transaction.ContractGeneric
}
var file_txproto_ethereum_ethereum_proto_depIdxs = []int32{
	5, // 0: hdwallet.ethereum.proto.Transaction.transfer:type_name -> hdwallet.ethereum.proto.Transaction.Transfer
	6, // 1: hdwallet.ethereum.proto.Transaction.erc20_transfer:type_name -> hdwallet.ethereum.proto.Transaction.ERC20Transfer
	7, // 2: hdwallet.ethereum.proto.Transaction.contract_generic:type_name -> hdwallet.ethereum.proto.Transaction.ContractGeneric
	0, // 3: hdwallet.ethereum.proto.SigningInput.transaction:type_name -> hdwallet.ethereum.proto.Transaction
	1, // 4: hdwallet.ethereum.proto.SigningInput.access_list:type_name -> hdwallet.ethereum.proto.Access
	2, // 5: hdwallet.ethereum.proto.SigningInput.authorization_list:type_name -> hdwallet.ethereum.proto.EthAuthorization
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_txproto_ethereum_ethereum_proto_init() }
func file_txproto_ethereum_ethereum_proto_init() {
	if File_txproto_ethereum_ethereum_proto != nil {
		return
	}
	file_txproto_ethereum_ethereum_proto_msgTypes[0].OneofWrappers = []any{
		(*Transaction_Transfer_)(nil),
		(*Transaction_Erc20Transfer)(nil),
		(*Transaction_ContractGeneric_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_ethereum_ethereum_proto_rawDesc), len(file_txproto_ethereum_ethereum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_ethereum_ethereum_proto_goTypes,
		DependencyIndexes: file_txproto_ethereum_ethereum_proto_depIdxs,
		MessageInfos:      file_txproto_ethereum_ethereum_proto_msgTypes,
	}.Build()
	File_txproto_ethereum_ethereum_proto = out.File
	file_txproto_ethereum_ethereum_proto_goTypes = nil
	file_txproto_ethereum_ethereum_proto_depIdxs = nil
}
