// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/tron/tron.proto

package tron

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceCode for Stake 2.0 operations.
type ResourceCode int32

const (
	ResourceCode_BANDWIDTH ResourceCode = 0
	ResourceCode_ENERGY    ResourceCode = 1
)

// Enum value maps for ResourceCode.
var (
	ResourceCode_name = map[int32]string{
		0: "BANDWIDTH",
		1: "ENERGY",
	}
	ResourceCode_value = map[string]int32{
		"BANDWIDTH": 0,
		"ENERGY":    1,
	}
)

func (x ResourceCode) Enum() *ResourceCode {
	p := new(ResourceCode)
	*p = x
	return p
}

func (x ResourceCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceCode) Descriptor() protoreflect.EnumDescriptor {
	return file_txproto_tron_tron_proto_enumTypes[0].Descriptor()
}

func (ResourceCode) Type() protoreflect.EnumType {
	return &file_txproto_tron_tron_proto_enumTypes[0]
}

func (x ResourceCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceCode.Descriptor instead.
func (ResourceCode) EnumDescriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{0}
}

// TRX transfer (TransferContract).
type TransferContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`          // base58check (T...)
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                // in SUN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferContract) Reset() {
	*x = TransferContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferContract) ProtoMessage() {}

func (x *TransferContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferContract.ProtoReflect.Descriptor instead.
func (*TransferContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{0}
}

func (x *TransferContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *TransferContract) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferContract) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// TRC-20 token transfer, built as a TriggerSmartContract calling the token's
// transfer(address,uint256). Addresses are base58check (T...).
type TransferTRC20Contract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // sender (T...)
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // the TRC-20 token contract (T...)
	ToAddress       string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`                   // recipient (T...)
	Amount          []byte                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                          // big-endian uint256
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferTRC20Contract) Reset() {
	*x = TransferTRC20Contract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTRC20Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTRC20Contract) ProtoMessage() {}

func (x *TransferTRC20Contract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTRC20Contract.ProtoReflect.Descriptor instead.
func (*TransferTRC20Contract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{1}
}

func (x *TransferTRC20Contract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *TransferTRC20Contract) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *TransferTRC20Contract) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferTRC20Contract) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

// TRC-10 token transfer (TransferAssetContract). Addresses are base58check (T...).
type TransferAssetContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetName     string                 `protobuf:"bytes,1,opt,name=asset_name,json=assetName,proto3" json:"asset_name,omitempty"`          // TRC-10 asset ID string, e.g. "1000001"
	OwnerAddress  string                 `protobuf:"bytes,2,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	ToAddress     string                 `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`          // base58check (T...)
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                                // token units
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferAssetContract) Reset() {
	*x = TransferAssetContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferAssetContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferAssetContract) ProtoMessage() {}

func (x *TransferAssetContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferAssetContract.ProtoReflect.Descriptor instead.
func (*TransferAssetContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{2}
}

func (x *TransferAssetContract) GetAssetName() string {
	if x != nil {
		return x.AssetName
	}
	return ""
}

func (x *TransferAssetContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *TransferAssetContract) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferAssetContract) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Stake 2.0: freeze TRX to obtain resources (BANDWIDTH or ENERGY).
type FreezeBalanceV2Contract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`     // base58check (T...)
	FrozenBalance int64                  `protobuf:"varint,2,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"` // SUN (1 TRX = 1,000,000 SUN)
	Resource      ResourceCode           `protobuf:"varint,3,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeBalanceV2Contract) Reset() {
	*x = FreezeBalanceV2Contract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeBalanceV2Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeBalanceV2Contract) ProtoMessage() {}

func (x *FreezeBalanceV2Contract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeBalanceV2Contract.ProtoReflect.Descriptor instead.
func (*FreezeBalanceV2Contract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{3}
}

func (x *FreezeBalanceV2Contract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *FreezeBalanceV2Contract) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *FreezeBalanceV2Contract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

// Stake 2.0: unfreeze previously frozen TRX.
type UnfreezeBalanceV2Contract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`           // base58check (T...)
	UnfreezeBalance int64                  `protobuf:"varint,2,opt,name=unfreeze_balance,json=unfreezeBalance,proto3" json:"unfreeze_balance,omitempty"` // SUN
	Resource        ResourceCode           `protobuf:"varint,3,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnfreezeBalanceV2Contract) Reset() {
	*x = UnfreezeBalanceV2Contract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeBalanceV2Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeBalanceV2Contract) ProtoMessage() {}

func (x *UnfreezeBalanceV2Contract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeBalanceV2Contract.ProtoReflect.Descriptor instead.
func (*UnfreezeBalanceV2Contract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{4}
}

func (x *UnfreezeBalanceV2Contract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *UnfreezeBalanceV2Contract) GetUnfreezeBalance() int64 {
	if x != nil {
		return x.UnfreezeBalance
	}
	return 0
}

func (x *UnfreezeBalanceV2Contract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

// Stake 2.0: delegate resources to another account.
type DelegateResourceContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	Resource        ResourceCode           `protobuf:"varint,2,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"`
	Balance         int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`                                       // SUN
	ReceiverAddress string                 `protobuf:"bytes,4,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"` // base58check (T...)
	Lock            bool                   `protobuf:"varint,5,opt,name=lock,proto3" json:"lock,omitempty"`                                             // true = lock delegation for 3 days
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DelegateResourceContract) Reset() {
	*x = DelegateResourceContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelegateResourceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegateResourceContract) ProtoMessage() {}

func (x *DelegateResourceContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegateResourceContract.ProtoReflect.Descriptor instead.
func (*DelegateResourceContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{5}
}

func (x *DelegateResourceContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *DelegateResourceContract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

func (x *DelegateResourceContract) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *DelegateResourceContract) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *DelegateResourceContract) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

// Stake 2.0: revoke delegated resources.
type UndelegateResourceContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	Resource        ResourceCode           `protobuf:"varint,2,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"`
	Balance         int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`                                       // SUN
	ReceiverAddress string                 `protobuf:"bytes,4,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"` // base58check (T...)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UndelegateResourceContract) Reset() {
	*x = UndelegateResourceContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndelegateResourceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndelegateResourceContract) ProtoMessage() {}

func (x *UndelegateResourceContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndelegateResourceContract.ProtoReflect.Descriptor instead.
func (*UndelegateResourceContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{6}
}

func (x *UndelegateResourceContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *UndelegateResourceContract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

func (x *UndelegateResourceContract) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UndelegateResourceContract) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

// Stake 2.0: withdraw unfrozen TRX after the 14-day unbonding period.
type WithdrawExpireUnfreezeContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawExpireUnfreezeContract) Reset() {
	*x = WithdrawExpireUnfreezeContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawExpireUnfreezeContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawExpireUnfreezeContract) ProtoMessage() {}

func (x *WithdrawExpireUnfreezeContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawExpireUnfreezeContract.ProtoReflect.Descriptor instead.
func (*WithdrawExpireUnfreezeContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawExpireUnfreezeContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

// One vote in a VoteWitnessContract.
type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteAddress   string                 `protobuf:"bytes,1,opt,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"` // base58check (T...) of the Super Representative
	VoteCount     int64                  `protobuf:"varint,2,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_txproto_tron_tron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{8}
}

func (x *Vote) GetVoteAddress() string {
	if x != nil {
		return x.VoteAddress
	}
	return ""
}

func (x *Vote) GetVoteCount() int64 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

// Vote for Super Representatives.
type VoteWitnessContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	Votes         []*Vote                `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes,omitempty"`
	Support       bool                   `protobuf:"varint,3,opt,name=support,proto3" json:"support,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteWitnessContract) Reset() {
	*x = VoteWitnessContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteWitnessContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteWitnessContract) ProtoMessage() {}

func (x *VoteWitnessContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteWitnessContract.ProtoReflect.Descriptor instead.
func (*VoteWitnessContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{9}
}

func (x *VoteWitnessContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *VoteWitnessContract) GetVotes() []*Vote {
	if x != nil {
		return x.Votes
	}
	return nil
}

func (x *VoteWitnessContract) GetSupport() bool {
	if x != nil {
		return x.Support
	}
	return false
}

// Legacy Stake 1.0: freeze TRX to obtain resources (BANDWIDTH or ENERGY).
type FreezeBalanceContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`            // base58check (T...)
	FrozenBalance   int64                  `protobuf:"varint,2,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"`        // SUN (1 TRX = 1,000,000 SUN)
	FrozenDuration  int64                  `protobuf:"varint,3,opt,name=frozen_duration,json=frozenDuration,proto3" json:"frozen_duration,omitempty"`     // days
	Resource        ResourceCode           `protobuf:"varint,4,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"` // BANDWIDTH or ENERGY
	ReceiverAddress string                 `protobuf:"bytes,5,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`   // optional delegate target; "" = self
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FreezeBalanceContract) Reset() {
	*x = FreezeBalanceContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeBalanceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeBalanceContract) ProtoMessage() {}

func (x *FreezeBalanceContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeBalanceContract.ProtoReflect.Descriptor instead.
func (*FreezeBalanceContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{10}
}

func (x *FreezeBalanceContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *FreezeBalanceContract) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

func (x *FreezeBalanceContract) GetFrozenDuration() int64 {
	if x != nil {
		return x.FrozenDuration
	}
	return 0
}

func (x *FreezeBalanceContract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

func (x *FreezeBalanceContract) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

// Legacy Stake 1.0: unfreeze previously frozen TRX.
type UnfreezeBalanceContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`            // base58check (T...)
	Resource        ResourceCode           `protobuf:"varint,2,opt,name=resource,proto3,enum=hdwallet.tron.proto.ResourceCode" json:"resource,omitempty"` // BANDWIDTH or ENERGY (default BANDWIDTH)
	ReceiverAddress string                 `protobuf:"bytes,3,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`   // optional delegate target; "" = self
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnfreezeBalanceContract) Reset() {
	*x = UnfreezeBalanceContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeBalanceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeBalanceContract) ProtoMessage() {}

func (x *UnfreezeBalanceContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeBalanceContract.ProtoReflect.Descriptor instead.
func (*UnfreezeBalanceContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{11}
}

func (x *UnfreezeBalanceContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *UnfreezeBalanceContract) GetResource() ResourceCode {
	if x != nil {
		return x.Resource
	}
	return ResourceCode_BANDWIDTH
}

func (x *UnfreezeBalanceContract) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

// Unfreeze TRC-10 (legacy asset) balance.
type UnfreezeAssetContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfreezeAssetContract) Reset() {
	*x = UnfreezeAssetContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfreezeAssetContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfreezeAssetContract) ProtoMessage() {}

func (x *UnfreezeAssetContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfreezeAssetContract.ProtoReflect.Descriptor instead.
func (*UnfreezeAssetContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{12}
}

func (x *UnfreezeAssetContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

// Claim SR / voting rewards (WithdrawBalanceContract).
type WithdrawBalanceContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBalanceContract) Reset() {
	*x = WithdrawBalanceContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBalanceContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBalanceContract) ProtoMessage() {}

func (x *WithdrawBalanceContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBalanceContract.ProtoReflect.Descriptor instead.
func (*WithdrawBalanceContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{13}
}

func (x *WithdrawBalanceContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

// TRC-10 asset voting (VoteAssetContract).
type VoteAssetContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...) or hex
	VoteAddress   []string               `protobuf:"bytes,2,rep,name=vote_address,json=voteAddress,proto3" json:"vote_address,omitempty"`    // T... or hex
	Support       bool                   `protobuf:"varint,3,opt,name=support,proto3" json:"support,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteAssetContract) Reset() {
	*x = VoteAssetContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteAssetContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteAssetContract) ProtoMessage() {}

func (x *VoteAssetContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteAssetContract.ProtoReflect.Descriptor instead.
func (*VoteAssetContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{14}
}

func (x *VoteAssetContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *VoteAssetContract) GetVoteAddress() []string {
	if x != nil {
		return x.VoteAddress
	}
	return nil
}

func (x *VoteAssetContract) GetSupport() bool {
	if x != nil {
		return x.Support
	}
	return false
}

func (x *VoteAssetContract) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Generic smart-contract call (TriggerSmartContract). Supports TRX value,
// arbitrary calldata, and TRC-10 value attachment.
type TriggerSmartContract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress    string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`          // T... or hex
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"` // T... or hex
	CallValue       int64                  `protobuf:"varint,3,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`                  // TRX (SUN) sent with the call
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                              // raw calldata
	CallTokenValue  int64                  `protobuf:"varint,5,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"` // TRC-10 amount sent with the call
	TokenId         int64                  `protobuf:"varint,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`                        // TRC-10 token id
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TriggerSmartContract) Reset() {
	*x = TriggerSmartContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSmartContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSmartContract) ProtoMessage() {}

func (x *TriggerSmartContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSmartContract.ProtoReflect.Descriptor instead.
func (*TriggerSmartContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerSmartContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *TriggerSmartContract) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *TriggerSmartContract) GetCallValue() int64 {
	if x != nil {
		return x.CallValue
	}
	return 0
}

func (x *TriggerSmartContract) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TriggerSmartContract) GetCallTokenValue() int64 {
	if x != nil {
		return x.CallTokenValue
	}
	return 0
}

func (x *TriggerSmartContract) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

// Block header reference values, used to compute ref_block_bytes / ref_block_hash.
type BlockHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxTrieRoot     []byte                 `protobuf:"bytes,2,opt,name=tx_trie_root,json=txTrieRoot,proto3" json:"tx_trie_root,omitempty"`
	ParentHash     []byte                 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Number         int64                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	WitnessAddress []byte                 `protobuf:"bytes,5,opt,name=witness_address,json=witnessAddress,proto3" json:"witness_address,omitempty"`
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_txproto_tron_tron_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{16}
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetTxTrieRoot() []byte {
	if x != nil {
		return x.TxTrieRoot
	}
	return nil
}

func (x *BlockHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockHeader) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockHeader) GetWitnessAddress() []byte {
	if x != nil {
		return x.WitnessAddress
	}
	return nil
}

func (x *BlockHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Transaction payload selector.
type Transaction struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timestamp   int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiration  int64                  `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	BlockHeader *BlockHeader           `protobuf:"bytes,3,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	FeeLimit    int64                  `protobuf:"varint,4,opt,name=fee_limit,json=feeLimit,proto3" json:"fee_limit,omitempty"`
	// Types that are valid to be assigned to ContractOneof:
	//
	//	*Transaction_Transfer
	//	*Transaction_TransferTrc20
	//	*Transaction_TransferAsset
	//	*Transaction_FreezeBalanceV2
	//	*Transaction_UnfreezeBalanceV2
	//	*Transaction_DelegateResource
	//	*Transaction_UndelegateResource
	//	*Transaction_VoteWitness
	//	*Transaction_WithdrawExpireUnfreeze
	//	*Transaction_TriggerSmartContract
	//	*Transaction_FreezeBalance
	//	*Transaction_UnfreezeBalance
	//	*Transaction_UnfreezeAsset
	//	*Transaction_WithdrawBalance
	//	*Transaction_VoteAsset
	ContractOneof isTransaction_ContractOneof `protobuf_oneof:"contract_oneof"`
	Memo          []byte                      `protobuf:"bytes,20,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_txproto_tron_tron_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{17}
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *Transaction) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *Transaction) GetFeeLimit() int64 {
	if x != nil {
		return x.FeeLimit
	}
	return 0
}

func (x *Transaction) GetContractOneof() isTransaction_ContractOneof {
	if x != nil {
		return x.ContractOneof
	}
	return nil
}

func (x *Transaction) GetTransfer() *TransferContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *Transaction) GetTransferTrc20() *TransferTRC20Contract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_TransferTrc20); ok {
			return x.TransferTrc20
		}
	}
	return nil
}

func (x *Transaction) GetTransferAsset() *TransferAssetContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_TransferAsset); ok {
			return x.TransferAsset
		}
	}
	return nil
}

func (x *Transaction) GetFreezeBalanceV2() *FreezeBalanceV2Contract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_FreezeBalanceV2); ok {
			return x.FreezeBalanceV2
		}
	}
	return nil
}

func (x *Transaction) GetUnfreezeBalanceV2() *UnfreezeBalanceV2Contract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_UnfreezeBalanceV2); ok {
			return x.UnfreezeBalanceV2
		}
	}
	return nil
}

func (x *Transaction) GetDelegateResource() *DelegateResourceContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_DelegateResource); ok {
			return x.DelegateResource
		}
	}
	return nil
}

func (x *Transaction) GetUndelegateResource() *UndelegateResourceContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_UndelegateResource); ok {
			return x.UndelegateResource
		}
	}
	return nil
}

func (x *Transaction) GetVoteWitness() *VoteWitnessContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_VoteWitness); ok {
			return x.VoteWitness
		}
	}
	return nil
}

func (x *Transaction) GetWithdrawExpireUnfreeze() *WithdrawExpireUnfreezeContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_WithdrawExpireUnfreeze); ok {
			return x.WithdrawExpireUnfreeze
		}
	}
	return nil
}

func (x *Transaction) GetTriggerSmartContract() *TriggerSmartContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_TriggerSmartContract); ok {
			return x.TriggerSmartContract
		}
	}
	return nil
}

func (x *Transaction) GetFreezeBalance() *FreezeBalanceContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_FreezeBalance); ok {
			return x.FreezeBalance
		}
	}
	return nil
}

func (x *Transaction) GetUnfreezeBalance() *UnfreezeBalanceContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_UnfreezeBalance); ok {
			return x.UnfreezeBalance
		}
	}
	return nil
}

func (x *Transaction) GetUnfreezeAsset() *UnfreezeAssetContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_UnfreezeAsset); ok {
			return x.UnfreezeAsset
		}
	}
	return nil
}

func (x *Transaction) GetWithdrawBalance() *WithdrawBalanceContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_WithdrawBalance); ok {
			return x.WithdrawBalance
		}
	}
	return nil
}

func (x *Transaction) GetVoteAsset() *VoteAssetContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_VoteAsset); ok {
			return x.VoteAsset
		}
	}
	return nil
}

func (x *Transaction) GetMemo() []byte {
	if x != nil {
		return x.Memo
	}
	return nil
}

type isTransaction_ContractOneof interface {
	isTransaction_ContractOneof()
}

type Transaction_Transfer struct {
	Transfer *TransferContract `protobuf:"bytes,5,opt,name=transfer,proto3,oneof"`
}

type Transaction_TransferTrc20 struct {
	TransferTrc20 *TransferTRC20Contract `protobuf:"bytes,6,opt,name=transfer_trc20,json=transferTrc20,proto3,oneof"`
}

type Transaction_TransferAsset struct {
	TransferAsset *TransferAssetContract `protobuf:"bytes,7,opt,name=transfer_asset,json=transferAsset,proto3,oneof"`
}

type Transaction_FreezeBalanceV2 struct {
	FreezeBalanceV2 *FreezeBalanceV2Contract `protobuf:"bytes,8,opt,name=freeze_balance_v2,json=freezeBalanceV2,proto3,oneof"`
}

type Transaction_UnfreezeBalanceV2 struct {
	UnfreezeBalanceV2 *UnfreezeBalanceV2Contract `protobuf:"bytes,9,opt,name=unfreeze_balance_v2,json=unfreezeBalanceV2,proto3,oneof"`
}

type Transaction_DelegateResource struct {
	DelegateResource *DelegateResourceContract `protobuf:"bytes,10,opt,name=delegate_resource,json=delegateResource,proto3,oneof"`
}

type Transaction_UndelegateResource struct {
	UndelegateResource *UndelegateResourceContract `protobuf:"bytes,11,opt,name=undelegate_resource,json=undelegateResource,proto3,oneof"`
}

type Transaction_VoteWitness struct {
	VoteWitness *VoteWitnessContract `protobuf:"bytes,12,opt,name=vote_witness,json=voteWitness,proto3,oneof"`
}

type Transaction_WithdrawExpireUnfreeze struct {
	WithdrawExpireUnfreeze *WithdrawExpireUnfreezeContract `protobuf:"bytes,13,opt,name=withdraw_expire_unfreeze,json=withdrawExpireUnfreeze,proto3,oneof"`
}

type Transaction_TriggerSmartContract struct {
	TriggerSmartContract *TriggerSmartContract `protobuf:"bytes,14,opt,name=trigger_smart_contract,json=triggerSmartContract,proto3,oneof"`
}

type Transaction_FreezeBalance struct {
	FreezeBalance *FreezeBalanceContract `protobuf:"bytes,15,opt,name=freeze_balance,json=freezeBalance,proto3,oneof"`
}

type Transaction_UnfreezeBalance struct {
	UnfreezeBalance *UnfreezeBalanceContract `protobuf:"bytes,16,opt,name=unfreeze_balance,json=unfreezeBalance,proto3,oneof"`
}

type Transaction_UnfreezeAsset struct {
	UnfreezeAsset *UnfreezeAssetContract `protobuf:"bytes,17,opt,name=unfreeze_asset,json=unfreezeAsset,proto3,oneof"`
}

type Transaction_WithdrawBalance struct {
	WithdrawBalance *WithdrawBalanceContract `protobuf:"bytes,18,opt,name=withdraw_balance,json=withdrawBalance,proto3,oneof"`
}

type Transaction_VoteAsset struct {
	VoteAsset *VoteAssetContract `protobuf:"bytes,19,opt,name=vote_asset,json=voteAsset,proto3,oneof"`
}

func (*Transaction_Transfer) isTransaction_ContractOneof() {}

func (*Transaction_TransferTrc20) isTransaction_ContractOneof() {}

func (*Transaction_TransferAsset) isTransaction_ContractOneof() {}

func (*Transaction_FreezeBalanceV2) isTransaction_ContractOneof() {}

func (*Transaction_UnfreezeBalanceV2) isTransaction_ContractOneof() {}

func (*Transaction_DelegateResource) isTransaction_ContractOneof() {}

func (*Transaction_UndelegateResource) isTransaction_ContractOneof() {}

func (*Transaction_VoteWitness) isTransaction_ContractOneof() {}

func (*Transaction_WithdrawExpireUnfreeze) isTransaction_ContractOneof() {}

func (*Transaction_TriggerSmartContract) isTransaction_ContractOneof() {}

func (*Transaction_FreezeBalance) isTransaction_ContractOneof() {}

func (*Transaction_UnfreezeBalance) isTransaction_ContractOneof() {}

func (*Transaction_UnfreezeAsset) isTransaction_ContractOneof() {}

func (*Transaction_WithdrawBalance) isTransaction_ContractOneof() {}

func (*Transaction_VoteAsset) isTransaction_ContractOneof() {}

// SigningInput mirrors a minimal subset of TW.Tron.Proto.SigningInput.
type SigningInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	RawJson       string                 `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"` // raw transaction JSON from a Tron node / DApp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_tron_tron_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{18}
}

func (x *SigningInput) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SigningInput) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// SigningOutput mirrors a minimal subset of TW.Tron.Proto.SigningOutput.
type SigningOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // txID = sha256(raw_data)
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`            // 65-byte recoverable signature
	RawData       []byte                 `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // protobuf-serialized raw transaction
	RefBlockBytes string                 `protobuf:"bytes,4,opt,name=ref_block_bytes,json=refBlockBytes,proto3" json:"ref_block_bytes,omitempty"`
	Json          string                 `protobuf:"bytes,5,opt,name=json,proto3" json:"json,omitempty"` // convenience JSON
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	RefBlockHash  []byte                 `protobuf:"bytes,7,opt,name=ref_block_hash,json=refBlockHash,proto3" json:"ref_block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_tron_tron_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{19}
}

func (x *SigningOutput) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SigningOutput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningOutput) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *SigningOutput) GetRefBlockBytes() string {
	if x != nil {
		return x.RefBlockBytes
	}
	return ""
}

func (x *SigningOutput) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SigningOutput) GetRefBlockHash() []byte {
	if x != nil {
		return x.RefBlockHash
	}
	return nil
}

var File_txproto_tron_tron_proto protoreflect.FileDescriptor

const file_txproto_tron_tron_proto_rawDesc = "" +
	"\n" +
	"\x17txproto/tron/tron.proto\x12\x13hdwallet.tron.proto\"n\n" +
	"\x10TransferContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\x9e\x01\n" +
	"\x15TransferTRC20Contract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\fR\x06amount\"\x92\x01\n" +
	"\x15TransferAssetContract\x12\x1d\n" +
	"\n" +
	"asset_name\x18\x01 \x01(\tR\tassetName\x12#\n" +
	"\rowner_address\x18\x02 \x01(\tR\fownerAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x03 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"\xa4\x01\n" +
	"\x17FreezeBalanceV2Contract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12%\n" +
	"\x0efrozen_balance\x18\x02 \x01(\x03R\rfrozenBalance\x12=\n" +
	"\bresource\x18\x03 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\"\xaa\x01\n" +
	"\x19UnfreezeBalanceV2Contract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12)\n" +
	"\x10unfreeze_balance\x18\x02 \x01(\x03R\x0funfreezeBalance\x12=\n" +
	"\bresource\x18\x03 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\"\xd7\x01\n" +
	"\x18DelegateResourceContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12=\n" +
	"\bresource\x18\x02 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12)\n" +
	"\x10receiver_address\x18\x04 \x01(\tR\x0freceiverAddress\x12\x12\n" +
	"\x04lock\x18\x05 \x01(\bR\x04lock\"\xc5\x01\n" +
	"\x1aUndelegateResourceContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12=\n" +
	"\bresource\x18\x02 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12)\n" +
	"\x10receiver_address\x18\x04 \x01(\tR\x0freceiverAddress\"E\n" +
	"\x1eWithdrawExpireUnfreezeContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\"H\n" +
	"\x04Vote\x12!\n" +
	"\fvote_address\x18\x01 \x01(\tR\vvoteAddress\x12\x1d\n" +
	"\n" +
	"vote_count\x18\x02 \x01(\x03R\tvoteCount\"\x85\x01\n" +
	"\x13VoteWitnessContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12/\n" +
	"\x05votes\x18\x02 \x03(\v2\x19.hdwallet.tron.proto.VoteR\x05votes\x12\x18\n" +
	"\asupport\x18\x03 \x01(\bR\asupport\"\xf6\x01\n" +
	"\x15FreezeBalanceContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12%\n" +
	"\x0efrozen_balance\x18\x02 \x01(\x03R\rfrozenBalance\x12'\n" +
	"\x0ffrozen_duration\x18\x03 \x01(\x03R\x0efrozenDuration\x12=\n" +
	"\bresource\x18\x04 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\x12)\n" +
	"\x10receiver_address\x18\x05 \x01(\tR\x0freceiverAddress\"\xa8\x01\n" +
	"\x17UnfreezeBalanceContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12=\n" +
	"\bresource\x18\x02 \x01(\x0e2!.hdwallet.tron.proto.ResourceCodeR\bresource\x12)\n" +
	"\x10receiver_address\x18\x03 \x01(\tR\x0freceiverAddress\"<\n" +
	"\x15UnfreezeAssetContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\">\n" +
	"\x17WithdrawBalanceContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\"\x8b\x01\n" +
	"\x11VoteAssetContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12!\n" +
	"\fvote_address\x18\x02 \x03(\tR\vvoteAddress\x12\x18\n" +
	"\asupport\x18\x03 \x01(\bR\asupport\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"\xde\x01\n" +
	"\x14TriggerSmartContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12\x1d\n" +
	"\n" +
	"call_value\x18\x03 \x01(\x03R\tcallValue\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12(\n" +
	"\x10call_token_value\x18\x05 \x01(\x03R\x0ecallTokenValue\x12\x19\n" +
	"\btoken_id\x18\x06 \x01(\x03R\atokenId\"\xc9\x01\n" +
	"\vBlockHeader\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12 \n" +
	"\ftx_trie_root\x18\x02 \x01(\fR\n" +
	"txTrieRoot\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\fR\n" +
	"parentHash\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x03R\x06number\x12'\n" +
	"\x0fwitness_address\x18\x05 \x01(\fR\x0ewitnessAddress\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"\x8e\f\n" +
	"\vTransaction\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"expiration\x18\x02 \x01(\x03R\n" +
	"expiration\x12C\n" +
	"\fblock_header\x18\x03 \x01(\v2 .hdwallet.tron.proto.BlockHeaderR\vblockHeader\x12\x1b\n" +
	"\tfee_limit\x18\x04 \x01(\x03R\bfeeLimit\x12C\n" +
	"\btransfer\x18\x05 \x01(\v2%.hdwallet.tron.proto.TransferContractH\x00R\btransfer\x12S\n" +
	"\x0etransfer_trc20\x18\x06 \x01(\v2*.hdwallet.tron.proto.TransferTRC20ContractH\x00R\rtransferTrc20\x12S\n" +
	"\x0etransfer_asset\x18\a \x01(\v2*.hdwallet.tron.proto.TransferAssetContractH\x00R\rtransferAsset\x12Z\n" +
	"\x11freeze_balance_v2\x18\b \x01(\v2,.hdwallet.tron.proto.FreezeBalanceV2ContractH\x00R\x0ffreezeBalanceV2\x12`\n" +
	"\x13unfreeze_balance_v2\x18\t \x01(\v2..hdwallet.tron.proto.UnfreezeBalanceV2ContractH\x00R\x11unfreezeBalanceV2\x12\\\n" +
	"\x11delegate_resource\x18\n" +
	" \x01(\v2-.hdwallet.tron.proto.DelegateResourceContractH\x00R\x10delegateResource\x12b\n" +
	"\x13undelegate_resource\x18\v \x01(\v2/.hdwallet.tron.proto.UndelegateResourceContractH\x00R\x12undelegateResource\x12M\n" +
	"\fvote_witness\x18\f \x01(\v2(.hdwallet.tron.proto.VoteWitnessContractH\x00R\vvoteWitness\x12o\n" +
	"\x18withdraw_expire_unfreeze\x18\r \x01(\v23.hdwallet.tron.proto.WithdrawExpireUnfreezeContractH\x00R\x16withdrawExpireUnfreeze\x12a\n" +
	"\x16trigger_smart_contract\x18\x0e \x01(\v2).hdwallet.tron.proto.TriggerSmartContractH\x00R\x14triggerSmartContract\x12S\n" +
	"\x0efreeze_balance\x18\x0f \x01(\v2*.hdwallet.tron.proto.FreezeBalanceContractH\x00R\rfreezeBalance\x12Y\n" +
	"\x10unfreeze_balance\x18\x10 \x01(\v2,.hdwallet.tron.proto.UnfreezeBalanceContractH\x00R\x0funfreezeBalance\x12S\n" +
	"\x0eunfreeze_asset\x18\x11 \x01(\v2*.hdwallet.tron.proto.UnfreezeAssetContractH\x00R\runfreezeAsset\x12Y\n" +
	"\x10withdraw_balance\x18\x12 \x01(\v2,.hdwallet.tron.proto.WithdrawBalanceContractH\x00R\x0fwithdrawBalance\x12G\n" +
	"\n" +
	"vote_asset\x18\x13 \x01(\v2&.hdwallet.tron.proto.VoteAssetContractH\x00R\tvoteAsset\x12\x12\n" +
	"\x04memo\x18\x14 \x01(\fR\x04memoB\x10\n" +
	"\x0econtract_oneof\"m\n" +
	"\fSigningInput\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .hdwallet.tron.proto.TransactionR\vtransaction\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\tR\arawJson\"\xd0\x01\n" +
	"\rSigningOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x19\n" +
	"\braw_data\x18\x03 \x01(\fR\arawData\x12&\n" +
	"\x0fref_block_bytes\x18\x04 \x01(\tR\rrefBlockBytes\x12\x12\n" +
	"\x04json\x18\x05 \x01(\tR\x04json\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12$\n" +
	"\x0eref_block_hash\x18\a \x01(\fR\frefBlockHash*)\n" +
	"\fResourceCode\x12\r\n" +
	"\tBANDWIDTH\x10\x00\x12\n" +
	"\n" +
	"\x06ENERGY\x10\x01B/Z-github.com/ranjbar-dev/hd-wallet/txproto/tronb\x06proto3"

var (
	file_txproto_tron_tron_proto_rawDescOnce sync.Once
	file_txproto_tron_tron_proto_rawDescData []byte
)

func file_txproto_tron_tron_proto_rawDescGZIP() []byte {
	file_txproto_tron_tron_proto_rawDescOnce.Do(func() {
		file_txproto_tron_tron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_tron_tron_proto_rawDesc), len(file_txproto_tron_tron_proto_rawDesc)))
	})
	return file_txproto_tron_tron_proto_rawDescData
}

var file_txproto_tron_tron_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_txproto_tron_tron_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_txproto_tron_tron_proto_goTypes = []any{
	(ResourceCode)(0),                      // 0: hdwallet.tron.proto.ResourceCode
	(*TransferContract)(nil),               // 1: hdwallet.tron.proto.TransferContract
	(*TransferTRC20Contract)(nil),          // 2: hdwallet.tron.proto.TransferTRC20Contract
	(*TransferAssetContract)(nil),          // 3: hdwallet.tron.proto.TransferAssetContract
	(*FreezeBalanceV2Contract)(nil),        // 4: hdwallet.tron.proto.FreezeBalanceV2Contract
	(*UnfreezeBalanceV2Contract)(nil),      // 5: hdwallet.tron.proto.UnfreezeBalanceV2Contract
	(*DelegateResourceContract)(nil),       // 6: hdwallet.tron.proto.DelegateResourceContract
	(*UndelegateResourceContract)(nil),     // 7: hdwallet.tron.proto.UndelegateResourceContract
	(*WithdrawExpireUnfreezeContract)(nil), // 8: hdwallet.tron.proto.WithdrawExpireUnfreezeContract
	(*Vote)(nil),                           // 9: hdwallet.tron.proto.Vote
	(*VoteWitnessContract)(nil),            // 10: hdwallet.tron.proto.VoteWitnessContract
	(*FreezeBalanceContract)(nil),          // 11: hdwallet.tron.proto.FreezeBalanceContract
	(*UnfreezeBalanceContract)(nil),        // 12: hdwallet.tron.proto.UnfreezeBalanceContract
	(*UnfreezeAssetContract)(nil),          // 13: hdwallet.tron.proto.UnfreezeAssetContract
	(*WithdrawBalanceContract)(nil),        // 14: hdwallet.tron.proto.WithdrawBalanceContract
	(*VoteAssetContract)(nil),              // 15: hdwallet.tron.proto.VoteAssetContract
	(*TriggerSmartContract)(nil),           // 16: hdwallet.tron.proto.TriggerSmartContract
	(*BlockHeader)(nil),                    // 17: hdwallet.tron.proto.BlockHeader
	(*Transaction)(nil),                    // 18: hdwallet.tron.proto.Transaction
	(*SigningInput)(nil),                   // 19: hdwallet.tron.proto.SigningInput
	(*SigningOutput)(nil),                  // 20: hdwallet.tron.proto.SigningOutput
}
var file_txproto_tron_tron_proto_depIdxs = []int32{
	0,  // 0: hdwallet.tron.proto.FreezeBalanceV2Contract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	0,  // 1: hdwallet.tron.proto.UnfreezeBalanceV2Contract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	0,  // 2: hdwallet.tron.proto.DelegateResourceContract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	0,  // 3: hdwallet.tron.proto.UndelegateResourceContract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	9,  // 4: hdwallet.tron.proto.VoteWitnessContract.votes:type_name -> hdwallet.tron.proto.Vote
	0,  // 5: hdwallet.tron.proto.FreezeBalanceContract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	0,  // 6: hdwallet.tron.proto.UnfreezeBalanceContract.resource:type_name -> hdwallet.tron.proto.ResourceCode
	17, // 7: hdwallet.tron.proto.Transaction.block_header:type_name -> hdwallet.tron.proto.BlockHeader
	1,  // 8: hdwallet.tron.proto.Transaction.transfer:type_name -> hdwallet.tron.proto.TransferContract
	2,  // 9: hdwallet.tron.proto.Transaction.transfer_trc20:type_name -> hdwallet.tron.proto.TransferTRC20Contract
	3,  // 10: hdwallet.tron.proto.Transaction.transfer_asset:type_name -> hdwallet.tron.proto.TransferAssetContract
	4,  // 11: hdwallet.tron.proto.Transaction.freeze_balance_v2:type_name -> hdwallet.tron.proto.FreezeBalanceV2Contract
	5,  // 12: hdwallet.tron.proto.Transaction.unfreeze_balance_v2:type_name -> hdwallet.tron.proto.UnfreezeBalanceV2Contract
	6,  // 13: hdwallet.tron.proto.Transaction.delegate_resource:type_name -> hdwallet.tron.proto.DelegateResourceContract
	7,  // 14: hdwallet.tron.proto.Transaction.undelegate_resource:type_name -> hdwallet.tron.proto.UndelegateResourceContract
	10, // 15: hdwallet.tron.proto.Transaction.vote_witness:type_name -> hdwallet.tron.proto.VoteWitnessContract
	8,  // 16: hdwallet.tron.proto.Transaction.withdraw_expire_unfreeze:type_name -> hdwallet.tron.proto.WithdrawExpireUnfreezeContract
	16, // 17: hdwallet.tron.proto.Transaction.trigger_smart_contract:type_name -> hdwallet.tron.proto.TriggerSmartContract
	11, // 18: hdwallet.tron.proto.Transaction.freeze_balance:type_name -> hdwallet.tron.proto.FreezeBalanceContract
	12, // 19: hdwallet.tron.proto.Transaction.unfreeze_balance:type_name -> hdwallet.tron.proto.UnfreezeBalanceContract
	13, // 20: hdwallet.tron.proto.Transaction.unfreeze_asset:type_name -> hdwallet.tron.proto.UnfreezeAssetContract
	14, // 21: hdwallet.tron.proto.Transaction.withdraw_balance:type_name -> hdwallet.tron.proto.WithdrawBalanceContract
	15, // 22: hdwallet.tron.proto.Transaction.vote_asset:type_name -> hdwallet.tron.proto.VoteAssetContract
	18, // 23: hdwallet.tron.proto.SigningInput.transaction:type_name -> hdwallet.tron.proto.Transaction
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_txproto_tron_tron_proto_init() }
func file_txproto_tron_tron_proto_init() {
	if File_txproto_tron_tron_proto != nil {
		return
	}
	file_txproto_tron_tron_proto_msgTypes[17].OneofWrappers = []any{
		(*Transaction_Transfer)(nil),
		(*Transaction_TransferTrc20)(nil),
		(*Transaction_TransferAsset)(nil),
		(*Transaction_FreezeBalanceV2)(nil),
		(*Transaction_UnfreezeBalanceV2)(nil),
		(*Transaction_DelegateResource)(nil),
		(*Transaction_UndelegateResource)(nil),
		(*Transaction_VoteWitness)(nil),
		(*Transaction_WithdrawExpireUnfreeze)(nil),
		(*Transaction_TriggerSmartContract)(nil),
		(*Transaction_FreezeBalance)(nil),
		(*Transaction_UnfreezeBalance)(nil),
		(*Transaction_UnfreezeAsset)(nil),
		(*Transaction_WithdrawBalance)(nil),
		(*Transaction_VoteAsset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_tron_tron_proto_rawDesc), len(file_txproto_tron_tron_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_tron_tron_proto_goTypes,
		DependencyIndexes: file_txproto_tron_tron_proto_depIdxs,
		EnumInfos:         file_txproto_tron_tron_proto_enumTypes,
		MessageInfos:      file_txproto_tron_tron_proto_msgTypes,
	}.Build()
	File_txproto_tron_tron_proto = out.File
	file_txproto_tron_tron_proto_goTypes = nil
	file_txproto_tron_tron_proto_depIdxs = nil
}
