// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/tron/tron.proto

package tron

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TRX transfer (TransferContract).
type TransferContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerAddress  string                 `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // base58check (T...)
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`          // base58check (T...)
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                // in SUN
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferContract) Reset() {
	*x = TransferContract{}
	mi := &file_txproto_tron_tron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferContract) ProtoMessage() {}

func (x *TransferContract) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferContract.ProtoReflect.Descriptor instead.
func (*TransferContract) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{0}
}

func (x *TransferContract) GetOwnerAddress() string {
	if x != nil {
		return x.OwnerAddress
	}
	return ""
}

func (x *TransferContract) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferContract) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Block header reference values, used to compute ref_block_bytes / ref_block_hash.
type BlockHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxTrieRoot     []byte                 `protobuf:"bytes,2,opt,name=tx_trie_root,json=txTrieRoot,proto3" json:"tx_trie_root,omitempty"`
	ParentHash     []byte                 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Number         int64                  `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	WitnessAddress []byte                 `protobuf:"bytes,5,opt,name=witness_address,json=witnessAddress,proto3" json:"witness_address,omitempty"`
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_txproto_tron_tron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlockHeader) GetTxTrieRoot() []byte {
	if x != nil {
		return x.TxTrieRoot
	}
	return nil
}

func (x *BlockHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockHeader) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BlockHeader) GetWitnessAddress() []byte {
	if x != nil {
		return x.WitnessAddress
	}
	return nil
}

func (x *BlockHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Transaction payload selector.
type Transaction struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Timestamp   int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Expiration  int64                  `protobuf:"varint,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	BlockHeader *BlockHeader           `protobuf:"bytes,3,opt,name=block_header,json=blockHeader,proto3" json:"block_header,omitempty"`
	FeeLimit    int64                  `protobuf:"varint,4,opt,name=fee_limit,json=feeLimit,proto3" json:"fee_limit,omitempty"`
	// Types that are valid to be assigned to ContractOneof:
	//
	//	*Transaction_Transfer
	ContractOneof isTransaction_ContractOneof `protobuf_oneof:"contract_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_txproto_tron_tron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *Transaction) GetBlockHeader() *BlockHeader {
	if x != nil {
		return x.BlockHeader
	}
	return nil
}

func (x *Transaction) GetFeeLimit() int64 {
	if x != nil {
		return x.FeeLimit
	}
	return 0
}

func (x *Transaction) GetContractOneof() isTransaction_ContractOneof {
	if x != nil {
		return x.ContractOneof
	}
	return nil
}

func (x *Transaction) GetTransfer() *TransferContract {
	if x != nil {
		if x, ok := x.ContractOneof.(*Transaction_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

type isTransaction_ContractOneof interface {
	isTransaction_ContractOneof()
}

type Transaction_Transfer struct {
	Transfer *TransferContract `protobuf:"bytes,5,opt,name=transfer,proto3,oneof"`
}

func (*Transaction_Transfer) isTransaction_ContractOneof() {}

// SigningInput mirrors a minimal subset of TW.Tron.Proto.SigningInput.
type SigningInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_tron_tron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{3}
}

func (x *SigningInput) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Tron.Proto.SigningOutput.
type SigningOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // txID = sha256(raw_data)
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`            // 65-byte recoverable signature
	RawData       []byte                 `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"` // protobuf-serialized raw transaction
	RefBlockBytes string                 `protobuf:"bytes,4,opt,name=ref_block_bytes,json=refBlockBytes,proto3" json:"ref_block_bytes,omitempty"`
	Json          string                 `protobuf:"bytes,5,opt,name=json,proto3" json:"json,omitempty"` // convenience JSON
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_tron_tron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_tron_tron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_tron_tron_proto_rawDescGZIP(), []int{4}
}

func (x *SigningOutput) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SigningOutput) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningOutput) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *SigningOutput) GetRefBlockBytes() string {
	if x != nil {
		return x.RefBlockBytes
	}
	return ""
}

func (x *SigningOutput) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_tron_tron_proto protoreflect.FileDescriptor

const file_txproto_tron_tron_proto_rawDesc = "" +
	"\n" +
	"\x17txproto/tron/tron.proto\x12\x13hdwallet.tron.proto\"n\n" +
	"\x10TransferContract\x12#\n" +
	"\rowner_address\x18\x01 \x01(\tR\fownerAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xc9\x01\n" +
	"\vBlockHeader\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12 \n" +
	"\ftx_trie_root\x18\x02 \x01(\fR\n" +
	"txTrieRoot\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\fR\n" +
	"parentHash\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x03R\x06number\x12'\n" +
	"\x0fwitness_address\x18\x05 \x01(\fR\x0ewitnessAddress\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"\x84\x02\n" +
	"\vTransaction\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1e\n" +
	"\n" +
	"expiration\x18\x02 \x01(\x03R\n" +
	"expiration\x12C\n" +
	"\fblock_header\x18\x03 \x01(\v2 .hdwallet.tron.proto.BlockHeaderR\vblockHeader\x12\x1b\n" +
	"\tfee_limit\x18\x04 \x01(\x03R\bfeeLimit\x12C\n" +
	"\btransfer\x18\x05 \x01(\v2%.hdwallet.tron.proto.TransferContractH\x00R\btransferB\x10\n" +
	"\x0econtract_oneof\"R\n" +
	"\fSigningInput\x12B\n" +
	"\vtransaction\x18\x01 \x01(\v2 .hdwallet.tron.proto.TransactionR\vtransaction\"\xaa\x01\n" +
	"\rSigningOutput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x19\n" +
	"\braw_data\x18\x03 \x01(\fR\arawData\x12&\n" +
	"\x0fref_block_bytes\x18\x04 \x01(\tR\rrefBlockBytes\x12\x12\n" +
	"\x04json\x18\x05 \x01(\tR\x04json\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB/Z-github.com/ranjbar-dev/hd-wallet/txproto/tronb\x06proto3"

var (
	file_txproto_tron_tron_proto_rawDescOnce sync.Once
	file_txproto_tron_tron_proto_rawDescData []byte
)

func file_txproto_tron_tron_proto_rawDescGZIP() []byte {
	file_txproto_tron_tron_proto_rawDescOnce.Do(func() {
		file_txproto_tron_tron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_tron_tron_proto_rawDesc), len(file_txproto_tron_tron_proto_rawDesc)))
	})
	return file_txproto_tron_tron_proto_rawDescData
}

var file_txproto_tron_tron_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_txproto_tron_tron_proto_goTypes = []any{
	(*TransferContract)(nil), // 0: hdwallet.tron.proto.TransferContract
	(*BlockHeader)(nil),      // 1: hdwallet.tron.proto.BlockHeader
	(*Transaction)(nil),      // 2: hdwallet.tron.proto.Transaction
	(*SigningInput)(nil),     // 3: hdwallet.tron.proto.SigningInput
	(*SigningOutput)(nil),    // 4: hdwallet.tron.proto.SigningOutput
}
var file_txproto_tron_tron_proto_depIdxs = []int32{
	1, // 0: hdwallet.tron.proto.Transaction.block_header:type_name -> hdwallet.tron.proto.BlockHeader
	0, // 1: hdwallet.tron.proto.Transaction.transfer:type_name -> hdwallet.tron.proto.TransferContract
	2, // 2: hdwallet.tron.proto.SigningInput.transaction:type_name -> hdwallet.tron.proto.Transaction
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_txproto_tron_tron_proto_init() }
func file_txproto_tron_tron_proto_init() {
	if File_txproto_tron_tron_proto != nil {
		return
	}
	file_txproto_tron_tron_proto_msgTypes[2].OneofWrappers = []any{
		(*Transaction_Transfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_tron_tron_proto_rawDesc), len(file_txproto_tron_tron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_tron_tron_proto_goTypes,
		DependencyIndexes: file_txproto_tron_tron_proto_depIdxs,
		MessageInfos:      file_txproto_tron_tron_proto_msgTypes,
	}.Build()
	File_txproto_tron_tron_proto = out.File
	file_txproto_tron_tron_proto_goTypes = nil
	file_txproto_tron_tron_proto_depIdxs = nil
}
