// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/algorand/algorand.proto

package algorand

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SigningInput mirrors a minimal subset of TW.Algorand.Proto.SigningInput,
// restricted to payment (type "pay") transactions.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Genesis hash of the network (32 bytes, mainnet or testnet).
	GenesisHash []byte `protobuf:"bytes,1,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	// Genesis ID string, e.g. "mainnet-v1.0". Optional; omitted from msgpack if empty.
	GenesisId string `protobuf:"bytes,2,opt,name=genesis_id,json=genesisId,proto3" json:"genesis_id,omitempty"`
	// First valid round.
	FirstValid uint64 `protobuf:"varint,3,opt,name=first_valid,json=firstValid,proto3" json:"first_valid,omitempty"`
	// Last valid round.
	LastValid uint64 `protobuf:"varint,4,opt,name=last_valid,json=lastValid,proto3" json:"last_valid,omitempty"`
	// Optional note field (up to 1024 bytes). Omitted from msgpack if empty.
	Note []byte `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	// Recipient public key (32 raw bytes, not the base32 address).
	To []byte `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	// Amount in microAlgos.
	Amount uint64 `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	// Fee in microAlgos.
	Fee           uint64 `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_algorand_algorand_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_algorand_algorand_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_algorand_algorand_proto_rawDescGZIP(), []int{0}
}

func (x *SigningInput) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *SigningInput) GetGenesisId() string {
	if x != nil {
		return x.GenesisId
	}
	return ""
}

func (x *SigningInput) GetFirstValid() uint64 {
	if x != nil {
		return x.FirstValid
	}
	return 0
}

func (x *SigningInput) GetLastValid() uint64 {
	if x != nil {
		return x.LastValid
	}
	return 0
}

func (x *SigningInput) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *SigningInput) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SigningInput) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SigningInput) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

// SigningOutput mirrors a minimal subset of TW.Algorand.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical msgpack encoding of the signed transaction.
	Encoded []byte `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Hex of encoded.
	EncodedHex string `protobuf:"bytes,2,opt,name=encoded_hex,json=encodedHex,proto3" json:"encoded_hex,omitempty"`
	// Error message; empty on success.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_algorand_algorand_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_algorand_algorand_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_algorand_algorand_proto_rawDescGZIP(), []int{1}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetEncodedHex() string {
	if x != nil {
		return x.EncodedHex
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_algorand_algorand_proto protoreflect.FileDescriptor

const file_txproto_algorand_algorand_proto_rawDesc = "" +
	"\n" +
	"\x1ftxproto/algorand/algorand.proto\x12\x17hdwallet.algorand.proto\"\xde\x01\n" +
	"\fSigningInput\x12!\n" +
	"\fgenesis_hash\x18\x01 \x01(\fR\vgenesisHash\x12\x1d\n" +
	"\n" +
	"genesis_id\x18\x02 \x01(\tR\tgenesisId\x12\x1f\n" +
	"\vfirst_valid\x18\x03 \x01(\x04R\n" +
	"firstValid\x12\x1d\n" +
	"\n" +
	"last_valid\x18\x04 \x01(\x04R\tlastValid\x12\x12\n" +
	"\x04note\x18\x05 \x01(\fR\x04note\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\fR\x02to\x12\x16\n" +
	"\x06amount\x18\a \x01(\x04R\x06amount\x12\x10\n" +
	"\x03fee\x18\b \x01(\x04R\x03fee\"`\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\x1f\n" +
	"\vencoded_hex\x18\x02 \x01(\tR\n" +
	"encodedHex\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB3Z1github.com/ranjbar-dev/hd-wallet/txproto/algorandb\x06proto3"

var (
	file_txproto_algorand_algorand_proto_rawDescOnce sync.Once
	file_txproto_algorand_algorand_proto_rawDescData []byte
)

func file_txproto_algorand_algorand_proto_rawDescGZIP() []byte {
	file_txproto_algorand_algorand_proto_rawDescOnce.Do(func() {
		file_txproto_algorand_algorand_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_algorand_algorand_proto_rawDesc), len(file_txproto_algorand_algorand_proto_rawDesc)))
	})
	return file_txproto_algorand_algorand_proto_rawDescData
}

var file_txproto_algorand_algorand_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_txproto_algorand_algorand_proto_goTypes = []any{
	(*SigningInput)(nil),  // 0: hdwallet.algorand.proto.SigningInput
	(*SigningOutput)(nil), // 1: hdwallet.algorand.proto.SigningOutput
}
var file_txproto_algorand_algorand_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_txproto_algorand_algorand_proto_init() }
func file_txproto_algorand_algorand_proto_init() {
	if File_txproto_algorand_algorand_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_algorand_algorand_proto_rawDesc), len(file_txproto_algorand_algorand_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_algorand_algorand_proto_goTypes,
		DependencyIndexes: file_txproto_algorand_algorand_proto_depIdxs,
		MessageInfos:      file_txproto_algorand_algorand_proto_msgTypes,
	}.Build()
	File_txproto_algorand_algorand_proto = out.File
	file_txproto_algorand_algorand_proto_goTypes = nil
	file_txproto_algorand_algorand_proto_depIdxs = nil
}
