// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/aptos/aptos.proto

package aptos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryFunction payload for an Aptos transaction.
type EntryFunction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte module address (raw bytes, not hex string).
	ModuleAddress []byte `protobuf:"bytes,1,opt,name=module_address,json=moduleAddress,proto3" json:"module_address,omitempty"`
	// Module name, e.g. "aptos_account".
	ModuleName string `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	// Function name, e.g. "transfer".
	FunctionName string `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	// BCS-encoded TypeTag bytes for each type argument. Empty for most transfers.
	TypeArgs [][]byte `protobuf:"bytes,4,rep,name=type_args,json=typeArgs,proto3" json:"type_args,omitempty"`
	// Raw argument bytes. Each arg is already BCS-length-prefixed when it is a
	// byte sequence; the signer re-wraps them with ULEB128(len) + bytes.
	Args          [][]byte `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryFunction) Reset() {
	*x = EntryFunction{}
	mi := &file_txproto_aptos_aptos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryFunction) ProtoMessage() {}

func (x *EntryFunction) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_aptos_aptos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryFunction.ProtoReflect.Descriptor instead.
func (*EntryFunction) Descriptor() ([]byte, []int) {
	return file_txproto_aptos_aptos_proto_rawDescGZIP(), []int{0}
}

func (x *EntryFunction) GetModuleAddress() []byte {
	if x != nil {
		return x.ModuleAddress
	}
	return nil
}

func (x *EntryFunction) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *EntryFunction) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *EntryFunction) GetTypeArgs() [][]byte {
	if x != nil {
		return x.TypeArgs
	}
	return nil
}

func (x *EntryFunction) GetArgs() [][]byte {
	if x != nil {
		return x.Args
	}
	return nil
}

// Structured native APT transfer (0x1::aptos_account::transfer). The library
// builds the EntryFunction internally — no hand-BCS'd args.
type TransferMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0x-prefixed 32-byte recipient account address.
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Amount to transfer, in octas.
	Amount        uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferMessage) Reset() {
	*x = TransferMessage{}
	mi := &file_txproto_aptos_aptos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferMessage) ProtoMessage() {}

func (x *TransferMessage) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_aptos_aptos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferMessage.ProtoReflect.Descriptor instead.
func (*TransferMessage) Descriptor() ([]byte, []int) {
	return file_txproto_aptos_aptos_proto_rawDescGZIP(), []int{1}
}

func (x *TransferMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferMessage) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// SigningInput mirrors a minimal subset of TW.Aptos.Proto.SigningInput.
type SigningInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Account sequence number (uint64 LE in BCS).
	SequenceNumber uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Gas limit.
	MaxGasAmount uint64 `protobuf:"varint,2,opt,name=max_gas_amount,json=maxGasAmount,proto3" json:"max_gas_amount,omitempty"`
	// Gas unit price in octas.
	GasUnitPrice uint64 `protobuf:"varint,3,opt,name=gas_unit_price,json=gasUnitPrice,proto3" json:"gas_unit_price,omitempty"`
	// Transaction expiration (Unix timestamp in seconds).
	ExpirationTimestampSecs uint64 `protobuf:"varint,4,opt,name=expiration_timestamp_secs,json=expirationTimestampSecs,proto3" json:"expiration_timestamp_secs,omitempty"`
	// Chain ID (u8).
	ChainId uint32 `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// The entry function payload. Mutually exclusive with transfer.
	EntryFunction *EntryFunction `protobuf:"bytes,6,opt,name=entry_function,json=entryFunction,proto3" json:"entry_function,omitempty"`
	// Structured native APT transfer. Mutually exclusive with entry_function.
	Transfer      *TransferMessage `protobuf:"bytes,7,opt,name=transfer,proto3" json:"transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_aptos_aptos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_aptos_aptos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_aptos_aptos_proto_rawDescGZIP(), []int{2}
}

func (x *SigningInput) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *SigningInput) GetMaxGasAmount() uint64 {
	if x != nil {
		return x.MaxGasAmount
	}
	return 0
}

func (x *SigningInput) GetGasUnitPrice() uint64 {
	if x != nil {
		return x.GasUnitPrice
	}
	return 0
}

func (x *SigningInput) GetExpirationTimestampSecs() uint64 {
	if x != nil {
		return x.ExpirationTimestampSecs
	}
	return 0
}

func (x *SigningInput) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *SigningInput) GetEntryFunction() *EntryFunction {
	if x != nil {
		return x.EntryFunction
	}
	return nil
}

func (x *SigningInput) GetTransfer() *TransferMessage {
	if x != nil {
		return x.Transfer
	}
	return nil
}

// SigningOutput mirrors a minimal subset of TW.Aptos.Proto.SigningOutput.
type SigningOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BCS-encoded SignedTransaction bytes.
	RawTxn []byte `protobuf:"bytes,1,opt,name=raw_txn,json=rawTxn,proto3" json:"raw_txn,omitempty"`
	// Hex of raw_txn.
	Encoded string `protobuf:"bytes,2,opt,name=encoded,proto3" json:"encoded,omitempty"`
	// Error message; empty on success.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_aptos_aptos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_aptos_aptos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_aptos_aptos_proto_rawDescGZIP(), []int{3}
}

func (x *SigningOutput) GetRawTxn() []byte {
	if x != nil {
		return x.RawTxn
	}
	return nil
}

func (x *SigningOutput) GetEncoded() string {
	if x != nil {
		return x.Encoded
	}
	return ""
}

func (x *SigningOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_txproto_aptos_aptos_proto protoreflect.FileDescriptor

const file_txproto_aptos_aptos_proto_rawDesc = "" +
	"\n" +
	"\x19txproto/aptos/aptos.proto\x12\x14hdwallet.aptos.proto\"\xad\x01\n" +
	"\rEntryFunction\x12%\n" +
	"\x0emodule_address\x18\x01 \x01(\fR\rmoduleAddress\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12#\n" +
	"\rfunction_name\x18\x03 \x01(\tR\ffunctionName\x12\x1b\n" +
	"\ttype_args\x18\x04 \x03(\fR\btypeArgs\x12\x12\n" +
	"\x04args\x18\x05 \x03(\fR\x04args\"9\n" +
	"\x0fTransferMessage\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"\xe9\x02\n" +
	"\fSigningInput\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04R\x0esequenceNumber\x12$\n" +
	"\x0emax_gas_amount\x18\x02 \x01(\x04R\fmaxGasAmount\x12$\n" +
	"\x0egas_unit_price\x18\x03 \x01(\x04R\fgasUnitPrice\x12:\n" +
	"\x19expiration_timestamp_secs\x18\x04 \x01(\x04R\x17expirationTimestampSecs\x12\x19\n" +
	"\bchain_id\x18\x05 \x01(\rR\achainId\x12J\n" +
	"\x0eentry_function\x18\x06 \x01(\v2#.hdwallet.aptos.proto.EntryFunctionR\rentryFunction\x12A\n" +
	"\btransfer\x18\a \x01(\v2%.hdwallet.aptos.proto.TransferMessageR\btransfer\"X\n" +
	"\rSigningOutput\x12\x17\n" +
	"\araw_txn\x18\x01 \x01(\fR\x06rawTxn\x12\x18\n" +
	"\aencoded\x18\x02 \x01(\tR\aencoded\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB0Z.github.com/ranjbar-dev/hd-wallet/txproto/aptosb\x06proto3"

var (
	file_txproto_aptos_aptos_proto_rawDescOnce sync.Once
	file_txproto_aptos_aptos_proto_rawDescData []byte
)

func file_txproto_aptos_aptos_proto_rawDescGZIP() []byte {
	file_txproto_aptos_aptos_proto_rawDescOnce.Do(func() {
		file_txproto_aptos_aptos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_aptos_aptos_proto_rawDesc), len(file_txproto_aptos_aptos_proto_rawDesc)))
	})
	return file_txproto_aptos_aptos_proto_rawDescData
}

var file_txproto_aptos_aptos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_txproto_aptos_aptos_proto_goTypes = []any{
	(*EntryFunction)(nil),   // 0: hdwallet.aptos.proto.EntryFunction
	(*TransferMessage)(nil), // 1: hdwallet.aptos.proto.TransferMessage
	(*SigningInput)(nil),    // 2: hdwallet.aptos.proto.SigningInput
	(*SigningOutput)(nil),   // 3: hdwallet.aptos.proto.SigningOutput
}
var file_txproto_aptos_aptos_proto_depIdxs = []int32{
	0, // 0: hdwallet.aptos.proto.SigningInput.entry_function:type_name -> hdwallet.aptos.proto.EntryFunction
	1, // 1: hdwallet.aptos.proto.SigningInput.transfer:type_name -> hdwallet.aptos.proto.TransferMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_txproto_aptos_aptos_proto_init() }
func file_txproto_aptos_aptos_proto_init() {
	if File_txproto_aptos_aptos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_aptos_aptos_proto_rawDesc), len(file_txproto_aptos_aptos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_aptos_aptos_proto_goTypes,
		DependencyIndexes: file_txproto_aptos_aptos_proto_depIdxs,
		MessageInfos:      file_txproto_aptos_aptos_proto_msgTypes,
	}.Build()
	File_txproto_aptos_aptos_proto = out.File
	file_txproto_aptos_aptos_proto_goTypes = nil
	file_txproto_aptos_aptos_proto_depIdxs = nil
}
