// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: txproto/polkadot/polkadot.proto

package polkadot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Era describes extrinsic mortality: the transaction is valid for `period`
// blocks starting from the checkpoint block whose hash is
// SigningInput.block_hash. Omit era entirely for an immortal extrinsic (then
// block_hash must equal genesis_hash).
type Era struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"` // number of the checkpoint block (block_hash's block)
	Period        uint64                 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`                              // validity window in blocks; rounded up to a power of two, clamped to 4..65536
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Era) Reset() {
	*x = Era{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Era) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Era) ProtoMessage() {}

func (x *Era) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Era.ProtoReflect.Descriptor instead.
func (*Era) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{0}
}

func (x *Era) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Era) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

// CallIndices overrides the (pallet, call) index pair of the encoded call.
// The defaults below target the current Polkadot relay-chain / Asset Hub
// runtimes; other Substrate chains (or a future runtime upgrade) may renumber
// pallets, in which case the caller supplies the indices from the chain's
// runtime metadata.
type CallIndices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleIndex   uint32                 `protobuf:"varint,1,opt,name=module_index,json=moduleIndex,proto3" json:"module_index,omitempty"` // pallet index
	MethodIndex   uint32                 `protobuf:"varint,2,opt,name=method_index,json=methodIndex,proto3" json:"method_index,omitempty"` // call index within the pallet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallIndices) Reset() {
	*x = CallIndices{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallIndices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallIndices) ProtoMessage() {}

func (x *CallIndices) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallIndices.ProtoReflect.Descriptor instead.
func (*CallIndices) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{1}
}

func (x *CallIndices) GetModuleIndex() uint32 {
	if x != nil {
		return x.ModuleIndex
	}
	return 0
}

func (x *CallIndices) GetMethodIndex() uint32 {
	if x != nil {
		return x.MethodIndex
	}
	return 0
}

// Balances.transfer_keep_alive — native DOT transfer that cannot reap the
// sender below the existential deposit. Default call indices (5, 3); override
// with call_indices for e.g. transfer_allow_death (5, 0).
type BalanceTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddress     string                 `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // SS58 recipient address
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                // amount in planck, big-endian (u128)
	CallIndices   *CallIndices           `protobuf:"bytes,3,opt,name=call_indices,json=callIndices,proto3" json:"call_indices,omitempty"` // optional (pallet, call) override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceTransfer) Reset() {
	*x = BalanceTransfer{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceTransfer) ProtoMessage() {}

func (x *BalanceTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceTransfer.ProtoReflect.Descriptor instead.
func (*BalanceTransfer) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceTransfer) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *BalanceTransfer) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BalanceTransfer) GetCallIndices() *CallIndices {
	if x != nil {
		return x.CallIndices
	}
	return nil
}

// Assets.transfer_keep_alive — pallet-assets token transfer on Polkadot Asset
// Hub (USDT: asset_id 1984, USDC: asset_id 1337). Default call indices
// (50, 9). Asset Hub uses MultiAddress encoding: set multi_address = true.
type AssetTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddress     string                 `protobuf:"bytes,1,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // SS58 recipient address
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                // token amount, big-endian (u128)
	AssetId       uint32                 `protobuf:"varint,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`            // pallet-assets numeric asset id (compact-encoded)
	CallIndices   *CallIndices           `protobuf:"bytes,4,opt,name=call_indices,json=callIndices,proto3" json:"call_indices,omitempty"` // optional (pallet, call) override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetTransfer) Reset() {
	*x = AssetTransfer{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetTransfer) ProtoMessage() {}

func (x *AssetTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetTransfer.ProtoReflect.Descriptor instead.
func (*AssetTransfer) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{3}
}

func (x *AssetTransfer) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *AssetTransfer) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AssetTransfer) GetAssetId() uint32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *AssetTransfer) GetCallIndices() *CallIndices {
	if x != nil {
		return x.CallIndices
	}
	return nil
}

// SigningInput carries everything a mortal Substrate extrinsic needs. The
// runtime context (spec_version, transaction_version, genesis_hash and the
// mortality checkpoint) comes from the caller — see SubstrateContextProvider
// in providers.go for the RPC mapping.
type SigningInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GenesisHash        []byte                 `protobuf:"bytes,1,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`                       // 32-byte chain genesis hash
	BlockHash          []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`                             // 32-byte mortality checkpoint hash; ignored (genesis is used) when era is absent
	Nonce              uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                     // account nonce
	SpecVersion        uint32                 `protobuf:"varint,4,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`                      // runtime spec version (state_getRuntimeVersion)
	TransactionVersion uint32                 `protobuf:"varint,5,opt,name=transaction_version,json=transactionVersion,proto3" json:"transaction_version,omitempty"` // runtime transaction version
	Tip                []byte                 `protobuf:"bytes,6,opt,name=tip,proto3" json:"tip,omitempty"`                                                          // optional tip in planck, big-endian (u128); empty = 0
	Era                *Era                   `protobuf:"bytes,7,opt,name=era,proto3" json:"era,omitempty"`                                                          // omit for an immortal extrinsic
	Network            uint32                 `protobuf:"varint,8,opt,name=network,proto3" json:"network,omitempty"`                                                 // SS58 network prefix of to_address (0 = Polkadot)
	// multi_address selects the MultiAddress account encoding (0x00 ‖ AccountId)
	// used by the Polkadot relay chain since spec_version 28 and by Asset Hub.
	// false = raw AccountId (matches the pinned TWC vector, spec_version 26).
	MultiAddress bool `protobuf:"varint,9,opt,name=multi_address,json=multiAddress,proto3" json:"multi_address,omitempty"`
	// Types that are valid to be assigned to MessageOneof:
	//
	//	*SigningInput_BalanceTransfer
	//	*SigningInput_AssetTransfer
	MessageOneof  isSigningInput_MessageOneof `protobuf_oneof:"message_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningInput) Reset() {
	*x = SigningInput{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningInput) ProtoMessage() {}

func (x *SigningInput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningInput.ProtoReflect.Descriptor instead.
func (*SigningInput) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{4}
}

func (x *SigningInput) GetGenesisHash() []byte {
	if x != nil {
		return x.GenesisHash
	}
	return nil
}

func (x *SigningInput) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SigningInput) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *SigningInput) GetSpecVersion() uint32 {
	if x != nil {
		return x.SpecVersion
	}
	return 0
}

func (x *SigningInput) GetTransactionVersion() uint32 {
	if x != nil {
		return x.TransactionVersion
	}
	return 0
}

func (x *SigningInput) GetTip() []byte {
	if x != nil {
		return x.Tip
	}
	return nil
}

func (x *SigningInput) GetEra() *Era {
	if x != nil {
		return x.Era
	}
	return nil
}

func (x *SigningInput) GetNetwork() uint32 {
	if x != nil {
		return x.Network
	}
	return 0
}

func (x *SigningInput) GetMultiAddress() bool {
	if x != nil {
		return x.MultiAddress
	}
	return false
}

func (x *SigningInput) GetMessageOneof() isSigningInput_MessageOneof {
	if x != nil {
		return x.MessageOneof
	}
	return nil
}

func (x *SigningInput) GetBalanceTransfer() *BalanceTransfer {
	if x != nil {
		if x, ok := x.MessageOneof.(*SigningInput_BalanceTransfer); ok {
			return x.BalanceTransfer
		}
	}
	return nil
}

func (x *SigningInput) GetAssetTransfer() *AssetTransfer {
	if x != nil {
		if x, ok := x.MessageOneof.(*SigningInput_AssetTransfer); ok {
			return x.AssetTransfer
		}
	}
	return nil
}

type isSigningInput_MessageOneof interface {
	isSigningInput_MessageOneof()
}

type SigningInput_BalanceTransfer struct {
	BalanceTransfer *BalanceTransfer `protobuf:"bytes,10,opt,name=balance_transfer,json=balanceTransfer,proto3,oneof"`
}

type SigningInput_AssetTransfer struct {
	AssetTransfer *AssetTransfer `protobuf:"bytes,11,opt,name=asset_transfer,json=assetTransfer,proto3,oneof"`
}

func (*SigningInput_BalanceTransfer) isSigningInput_MessageOneof() {}

func (*SigningInput_AssetTransfer) isSigningInput_MessageOneof() {}

type SigningOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       []byte                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`                         // SCALE-encoded signed extrinsic (UncheckedExtrinsic v4)
	EncodedHex    string                 `protobuf:"bytes,2,opt,name=encoded_hex,json=encodedHex,proto3" json:"encoded_hex,omitempty"` // "0x"-prefixed hex — the author_submitExtrinsic parameter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningOutput) Reset() {
	*x = SigningOutput{}
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningOutput) ProtoMessage() {}

func (x *SigningOutput) ProtoReflect() protoreflect.Message {
	mi := &file_txproto_polkadot_polkadot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningOutput.ProtoReflect.Descriptor instead.
func (*SigningOutput) Descriptor() ([]byte, []int) {
	return file_txproto_polkadot_polkadot_proto_rawDescGZIP(), []int{5}
}

func (x *SigningOutput) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

func (x *SigningOutput) GetEncodedHex() string {
	if x != nil {
		return x.EncodedHex
	}
	return ""
}

var File_txproto_polkadot_polkadot_proto protoreflect.FileDescriptor

const file_txproto_polkadot_polkadot_proto_rawDesc = "" +
	"\n" +
	"\x1ftxproto/polkadot/polkadot.proto\x12\x17hdwallet.polkadot.proto\"@\n" +
	"\x03Era\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x16\n" +
	"\x06period\x18\x02 \x01(\x04R\x06period\"S\n" +
	"\vCallIndices\x12!\n" +
	"\fmodule_index\x18\x01 \x01(\rR\vmoduleIndex\x12!\n" +
	"\fmethod_index\x18\x02 \x01(\rR\vmethodIndex\"\x8f\x01\n" +
	"\x0fBalanceTransfer\x12\x1d\n" +
	"\n" +
	"to_address\x18\x01 \x01(\tR\ttoAddress\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12G\n" +
	"\fcall_indices\x18\x03 \x01(\v2$.hdwallet.polkadot.proto.CallIndicesR\vcallIndices\"\xa8\x01\n" +
	"\rAssetTransfer\x12\x1d\n" +
	"\n" +
	"to_address\x18\x01 \x01(\tR\ttoAddress\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\rR\aassetId\x12G\n" +
	"\fcall_indices\x18\x04 \x01(\v2$.hdwallet.polkadot.proto.CallIndicesR\vcallIndices\"\xf4\x03\n" +
	"\fSigningInput\x12!\n" +
	"\fgenesis_hash\x18\x01 \x01(\fR\vgenesisHash\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12!\n" +
	"\fspec_version\x18\x04 \x01(\rR\vspecVersion\x12/\n" +
	"\x13transaction_version\x18\x05 \x01(\rR\x12transactionVersion\x12\x10\n" +
	"\x03tip\x18\x06 \x01(\fR\x03tip\x12.\n" +
	"\x03era\x18\a \x01(\v2\x1c.hdwallet.polkadot.proto.EraR\x03era\x12\x18\n" +
	"\anetwork\x18\b \x01(\rR\anetwork\x12#\n" +
	"\rmulti_address\x18\t \x01(\bR\fmultiAddress\x12U\n" +
	"\x10balance_transfer\x18\n" +
	" \x01(\v2(.hdwallet.polkadot.proto.BalanceTransferH\x00R\x0fbalanceTransfer\x12O\n" +
	"\x0easset_transfer\x18\v \x01(\v2&.hdwallet.polkadot.proto.AssetTransferH\x00R\rassetTransferB\x0f\n" +
	"\rmessage_oneof\"J\n" +
	"\rSigningOutput\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\x12\x1f\n" +
	"\vencoded_hex\x18\x02 \x01(\tR\n" +
	"encodedHexB3Z1github.com/ranjbar-dev/hd-wallet/txproto/polkadotb\x06proto3"

var (
	file_txproto_polkadot_polkadot_proto_rawDescOnce sync.Once
	file_txproto_polkadot_polkadot_proto_rawDescData []byte
)

func file_txproto_polkadot_polkadot_proto_rawDescGZIP() []byte {
	file_txproto_polkadot_polkadot_proto_rawDescOnce.Do(func() {
		file_txproto_polkadot_polkadot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_txproto_polkadot_polkadot_proto_rawDesc), len(file_txproto_polkadot_polkadot_proto_rawDesc)))
	})
	return file_txproto_polkadot_polkadot_proto_rawDescData
}

var file_txproto_polkadot_polkadot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_txproto_polkadot_polkadot_proto_goTypes = []any{
	(*Era)(nil),             // 0: hdwallet.polkadot.proto.Era
	(*CallIndices)(nil),     // 1: hdwallet.polkadot.proto.CallIndices
	(*BalanceTransfer)(nil), // 2: hdwallet.polkadot.proto.BalanceTransfer
	(*AssetTransfer)(nil),   // 3: hdwallet.polkadot.proto.AssetTransfer
	(*SigningInput)(nil),    // 4: hdwallet.polkadot.proto.SigningInput
	(*SigningOutput)(nil),   // 5: hdwallet.polkadot.proto.SigningOutput
}
var file_txproto_polkadot_polkadot_proto_depIdxs = []int32{
	1, // 0: hdwallet.polkadot.proto.BalanceTransfer.call_indices:type_name -> hdwallet.polkadot.proto.CallIndices
	1, // 1: hdwallet.polkadot.proto.AssetTransfer.call_indices:type_name -> hdwallet.polkadot.proto.CallIndices
	0, // 2: hdwallet.polkadot.proto.SigningInput.era:type_name -> hdwallet.polkadot.proto.Era
	2, // 3: hdwallet.polkadot.proto.SigningInput.balance_transfer:type_name -> hdwallet.polkadot.proto.BalanceTransfer
	3, // 4: hdwallet.polkadot.proto.SigningInput.asset_transfer:type_name -> hdwallet.polkadot.proto.AssetTransfer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_txproto_polkadot_polkadot_proto_init() }
func file_txproto_polkadot_polkadot_proto_init() {
	if File_txproto_polkadot_polkadot_proto != nil {
		return
	}
	file_txproto_polkadot_polkadot_proto_msgTypes[4].OneofWrappers = []any{
		(*SigningInput_BalanceTransfer)(nil),
		(*SigningInput_AssetTransfer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_txproto_polkadot_polkadot_proto_rawDesc), len(file_txproto_polkadot_polkadot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_txproto_polkadot_polkadot_proto_goTypes,
		DependencyIndexes: file_txproto_polkadot_polkadot_proto_depIdxs,
		MessageInfos:      file_txproto_polkadot_polkadot_proto_msgTypes,
	}.Build()
	File_txproto_polkadot_polkadot_proto = out.File
	file_txproto_polkadot_polkadot_proto_goTypes = nil
	file_txproto_polkadot_polkadot_proto_depIdxs = nil
}
